#!/usr/bin/env python3
"""Build the printable controls quick reference, and check that the control sources agree.

    python tools/controls-sheet/build_sheet.py            check, then write controls-sheet.html
                                                          and refresh the generated table in
                                                          docs/CONTROLS.md
    python tools/controls-sheet/build_sheet.py --check    check only (also: is the CONTROLS.md
                                                          table current?). Exit 1 on any finding.
    python tools/controls-sheet/build_sheet.py --extract-stock <GOG input.map>
                                                          rewrite stock-2.1.0.17.json

Standard library only. tools\\controls-sheet\\build.ps1 runs this, the input.map lint and the PDF.

Sources, each read fresh on every run (nothing is copied by hand that can be parsed):
  controls/input.map            native bindings (keyboard, mouse buttons, analog axes)
  i76-remap.ahk                 wheel tables (gWheelBase / gWheelAlt / gWheelHat / gWheelHatAlt /
                                gWheelHoldSet), mouse buttons 4 / 5 (XButton1 / XButton2), the
                                '@pad' lines and the keys the XIPoll code sends
  i76-ch-fighterstick.ahk       BTN / POV / AXIS tables (control, action, key)
  PLAY-i76.ps1                  -WheelUp / -WheelDown defaults (mouse wheel)
  controls-sheet.json           labels, groups, physical names, what each layer control is MEANT
                                to do, the allow-list of shared keys, the known mismatches
  stock-2.1.0.17.json           GOG's 1997 bindings, for the comparison page

The build FAILS (exit 1, every finding listed) when:
  1. an action in controls-sheet.json is not in the map, or an action in the map has no entry;
  2. a key a layer sends is not bound in the map (unless listed under known_mismatches);
  3. two actions share a key in the map and are not an allowed set;
  4. controls-sheet.json disagrees with the parsed .ahk (a pad entry without its @pad line, a
     @pad line without an entry, a key the code sends that no entry claims, a key bound to a
     different action than 'expect' says, a wheel button the tables do not have ...);
  5. a known_mismatches entry is no longer a mismatch (the list must stay true).
"""
import datetime, hashlib, html, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
MAP = os.path.join(REPO, "controls", "input.map")
REMAP = os.path.join(REPO, "i76-remap.ahk")
STICK = os.path.join(REPO, "i76-ch-fighterstick.ahk")
PLAY = os.path.join(REPO, "PLAY-i76.ps1")
DATA = os.path.join(HERE, "controls-sheet.json")
STOCK = os.path.join(HERE, "stock-2.1.0.17.json")
OUT_HTML = os.path.join(HERE, "controls-sheet.html")
CONTROLS_MD = os.path.join(REPO, "docs", "CONTROLS.md")
MD_BEGIN = "<!-- BEGIN generated by tools/controls-sheet/build_sheet.py: stock-vs-ours. Do not edit by hand. -->"
MD_END = "<!-- END generated: stock-vs-ours -->"

MODS = ("shift", "control")


def read(path):
    with open(path, encoding="utf-8", errors="replace", newline="") as f:
        return f.read().replace("\r\n", "\n")


# ----------------------------------------------------------------------------- input.map
def parse_map_text(text):
    """[{action, lines: [[sign, device, token], ...]}, ...] in file order."""
    blocks, action, cur = [], None, None
    for raw in text.split("\n"):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        m = re.match(r"^(\S+)\s*{", line)
        if m:
            action, cur = m.group(1), []
            continue
        if line.startswith("}"):
            if action is not None:
                blocks.append({"action": action, "lines": cur})
            action, cur = None, None
            continue
        m = re.match(r"^([+-])\s+(\S+)\s+(\S+)$", line)
        if m and cur is not None:
            cur.append([m.group(1), m.group(2), m.group(3)])
    return blocks


class Binding:
    """One block of the map: an action and how it is triggered."""
    def __init__(self, action, lines):
        self.action = action.lower()
        self.analog = None
        self.dev = self.tok = None
        self.mods = frozenset()
        analog = [l for l in lines if "/" in l[2]]
        if analog:
            self.analog = (analog[0][1].lower(), analog[0][2])
            return
        plus = [l for l in lines if l[0] == "+"]
        main = [l for l in plus if not (l[1].lower() == "keyboard" and l[2].lower() in MODS)]
        self.mods = frozenset(l[2].lower() for l in plus if l[1].lower() == "keyboard" and l[2].lower() in MODS)
        if main:
            self.dev, self.tok = main[0][1].lower(), main[0][2]

    @property
    def chord(self):
        return (self.dev, self.tok.lower(), self.mods) if self.tok else None


def bindings_of(blocks):
    return [Binding(b["action"], b["lines"]) for b in blocks]


def index_by_key(bindings):
    """(device, token.lower()) -> [action, ...] for bindings WITHOUT a modifier chord."""
    idx = {}
    for b in bindings:
        if b.tok and not b.mods:
            idx.setdefault((b.dev, b.tok.lower()), []).append(b.action)
    return idx


# ----------------------------------------------------------------------------- AutoHotkey
DIGITS = {"1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five",
          "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine", "0": "Zero"}
AHK_NAMED = {"enter": "Enter", "tab": "Tab", "space": "Space", ".": "Period", ",": "Comma",
             "-": "Minus", "=": "Equal", "up": "GreyUpArrow", "down": "GreyDownArrow",
             "left": "GreyLeftArrow", "right": "GreyRightArrow"}


def ahk_key(k):
    """An AutoHotkey key name -> ('keyboard'|'mouse'|'fixed', map token)."""
    kl = k.lower()
    if kl == "lbutton":
        return ("mouse", "LeftBtn")
    if kl in ("esc", "escape"):
        return ("fixed", "Esc")
    if re.fullmatch(r"f\d+", kl):
        return ("fixed", k.upper())
    if k in DIGITS:
        return ("keyboard", DIGITS[k])
    if kl in AHK_NAMED:
        return ("keyboard", AHK_NAMED[kl])
    if re.fullmatch(r"[a-z]", kl):
        return ("keyboard", k.upper())
    return ("keyboard", k)          # already a map token (the Fighterstick tables use those)


def ahk_table(src, name):
    """gName := {1: "h", 2: "Enter" ...} with ', ...' continuation lines -> {key: value}."""
    m = re.search(r"^%s\s*:=\s*\{(.*?)\}" % re.escape(name), src, re.M | re.S)
    if not m:
        return None
    out = {}
    for k, s, n in re.findall(r"(\d+)\s*:\s*(?:\"([^\"]*)\"|(\d+))", m.group(1)):
        out[k] = s if s != "" or not n else n
    return out


def parse_remap(src):
    r = {"findings": []}
    for name in ("gWheelBase", "gWheelAlt", "gWheelHoldSet", "gWheelHat", "gWheelHatAlt"):
        r[name] = ahk_table(src, name)
        if r[name] is None:
            r["findings"].append("i76-remap.ahk: table %s not found (the parser needs '%s := {...}')" % (name, name))
            r[name] = {}
    m = re.search(r"^gWheelShiftBtn\s*:=\s*(\d+)", src, re.M)
    r["shift_btn"] = m.group(1) if m else None
    if not m:
        r["findings"].append("i76-remap.ahk: gWheelShiftBtn not found")
    r["xbuttons"] = dict(re.findall(r"^(XButton\d)::(\S+)", src, re.M))
    r["pad_lines"] = {}
    for m in re.finditer(r"^;\s*@pad\s+([^:]+):\s*(.+)$", src, re.M):
        r["pad_lines"][m.group(1).strip()] = m.group(2).strip()
    # keys the pad code sends: the XIPoll section up to the rumble mixer, plus the right-stick glance
    keys = set()
    a = src.find("\nXIPoll:")
    b = src.find("; ---- rumble mixer", a)
    if a < 0 or b < 0:
        r["findings"].append("i76-remap.ahk: XIPoll section (from 'XIPoll:' to '; ---- rumble mixer') not found")
    else:
        sec = "\n".join(l.split(" ;", 1)[0] for l in src[a:b].split("\n") if not l.lstrip().startswith(";"))
        keys |= set(re.findall(r"RSGSet\(\"([^\"]+)\"", sec))
        for k in re.findall(r"^\s*SendEvent,\s*(\S+)\s*$", sec, re.M):
            k = k.strip("{}")
            if "%" not in k:
                keys.add(k)
        if re.search(r"^\s*Click\s*$", sec, re.M):
            keys.add("LButton")
        for lst in re.findall(r"StrSplit\(\"([^\"]+)\"", sec):
            keys |= set(lst.split(","))
        for x, y in re.findall(r"\?\s*\"(F\d+)\"\s*:\s*\"(F\d+)\"", sec):
            keys |= {x, y}
    g = re.search(r"^RStickGlance:(.*?)^return", src, re.M | re.S)
    if g:
        keys |= set(re.findall(r"RSGHys\(\"([^\"]+)\"", g.group(1)))
    r["pad_keys"] = keys
    return r


def parse_stick(src):
    s = {"btn": {}, "pov": [], "axis": [], "findings": []}
    for n, ctl, act, key in re.findall(
            r"^BTN\[(\d+)\]\s*:=\s*\{ctl:\s*\"([^\"]*)\",\s*act:\s*\"([^\"]*)\",\s*key:\s*\"([^\"]*)\"\}", src, re.M):
        s["btn"][int(n)] = {"ctl": ctl.strip(), "act": act, "key": key}
    for ctl, act, key in re.findall(
            r"^POV\.Push\(\{ctl:\s*\"([^\"]*)\",\s*act:\s*\"([^\"]*)\",\s*key:\s*\"([^\"]*)\"\}\)", src, re.M):
        s["pov"].append({"ctl": ctl.strip(), "act": act, "key": key})
    for body in re.findall(r"^AXIS\.Push\(\{(.*?)\}\)", src, re.M):
        d = dict(re.findall(r"(\w+):\s*\"?([^\",]+)\"?", body))
        s["axis"].append({k: v.strip() for k, v in d.items()})
    if not s["btn"] or len(s["pov"]) != 4 or len(s["axis"]) != 4:
        s["findings"].append("i76-ch-fighterstick.ahk: expected BTN[n] entries, 4 POV.Push and 4 AXIS.Push lines; found %d / %d / %d"
                             % (len(s["btn"]), len(s["pov"]), len(s["axis"])))
    return s


def parse_play(src):
    out = {}
    for name in ("WheelUp", "WheelDown"):
        m = re.search(r"\[string\]\$%s\s*=\s*\"([^\"]*)\"" % name, src)
        out[name] = m.group(1) if m else None
    return out


# ----------------------------------------------------------------------------- the model + checks
class Model:
    pass


def load():
    M = Model()
    M.findings = []
    M.data = json.loads(read(DATA))
    M.map_bytes = open(MAP, "rb").read()
    M.map_md5 = hashlib.md5(M.map_bytes).hexdigest()
    M.blocks = parse_map_text(read(MAP))
    M.bindings = bindings_of(M.blocks)
    M.by_key = index_by_key(M.bindings)
    M.stock = json.loads(read(STOCK))
    M.stock_bindings = bindings_of(M.stock["blocks"])
    M.remap = parse_remap(read(REMAP))
    M.stick = parse_stick(read(STICK))
    M.play = parse_play(read(PLAY))
    M.findings += M.remap["findings"] + M.stick["findings"]
    M.actions = {k.lower(): v for k, v in M.data["actions"].items() if not k.startswith("_")}
    M.stock_only = {k.lower(): v for k, v in M.data["stock_only_actions"].items() if not k.startswith("_")}
    M.fixed = {k: v for k, v in M.data["fixed_keys"].items() if not k.startswith("_")}
    M.groups = {g["id"]: g for g in M.data["groups"]}
    M.known = {e["id"]: e["what"] for e in M.data["known_mismatches"]["list"]}
    M.mismatches = {}            # id -> text, the ones actually found
    return M


def label(M, action):
    a = M.actions.get(action) or M.stock_only.get(action)
    return a["label"] if a else action


def resolve(M, layer, control, key, expect):
    """What a key sent by a layer does on the map. Records findings / mismatches.
    Returns (text, ok): text for the sheet, ok False when the key does nothing."""
    dev, tok = ahk_key(key)
    if dev == "fixed":
        if tok not in M.fixed:
            M.findings.append("%s %s sends %s, which is not in the map and not under fixed_keys in controls-sheet.json" % (layer, control, tok))
            return (tok, False)
        if expect:
            M.findings.append("%s %s: controls-sheet.json expects action '%s' but %s is an engine key outside the map (expect must be null)" % (layer, control, expect, tok))
        return (M.fixed[tok]["label"], True)
    acts = M.by_key.get((dev, tok.lower()), [])
    exp = expect.lower() if expect else None
    if exp and exp not in M.actions and exp not in M.stock_only:
        M.findings.append("%s %s: controls-sheet.json expects '%s', which is not an action name known to this file" % (layer, control, expect))
    if not acts:
        mid = "%s:%s:%s" % (layer, control, tok)
        what = "%s %s sends %s%s; the map binds nothing to that key" % (
            layer, control, pretty(tok), (" (meant: %s)" % label(M, exp)) if exp else "")
        M.mismatches[mid] = what
        if mid not in M.known:
            M.findings.append("KEY NOT BOUND IN THE MAP: %s. Bind it in controls/input.map, change the layer, or list id '%s' under known_mismatches" % (what, mid))
        return ((label(M, exp) if exp else pretty(tok)), False)
    if exp and exp not in acts:
        M.findings.append("%s %s sends %s, which the map binds to %s; controls-sheet.json says it is meant to be '%s'" % (
            layer, control, pretty(tok), " + ".join(acts), exp))
    return (" + ".join(dict.fromkeys(label(M, a) for a in acts)), True)


def check(M):
    F = M.findings
    map_actions = {b.action for b in M.bindings}
    # 1. data <-> map
    for a in sorted(set(M.actions) - map_actions):
        F.append("action '%s' is in controls-sheet.json but not in controls/input.map" % a)
    for a in sorted(map_actions - set(M.actions)):
        F.append("action '%s' is in controls/input.map but has no entry in controls-sheet.json (add its label and group)" % a)
    for a, v in list(M.actions.items()) + list(M.stock_only.items()) + list(M.fixed.items()):
        if v.get("group") not in M.groups:
            F.append("'%s': unknown group '%s' in controls-sheet.json" % (a, v.get("group")))
    for a in sorted(M.stock_only):
        if a in map_actions:
            F.append("'%s' is under stock_only_actions but controls/input.map binds it: move it to actions" % a)
    stock_actions = {b.action for b in M.stock_bindings}
    for a in sorted(stock_actions - set(M.actions) - set(M.stock_only)):
        F.append("stock action '%s' has no label (add it to actions or stock_only_actions)" % a)

    # 3. shared keys
    allowed = [set(x.lower() for x in s) for s in M.data["allow_shared_keys"]["sets"]]
    by_chord = {}
    for b in M.bindings:
        if b.chord:
            by_chord.setdefault(b.chord, set()).add(b.action)
    for chord, acts in sorted(by_chord.items(), key=str):
        if len(acts) > 1 and not any(acts <= s for s in allowed):
            F.append("actions %s share %s in the map and are not an allowed set (allow_shared_keys)" % (
                " + ".join(sorted(acts)), chord_text(chord[1], chord[2], chord[0])))
    for b in M.bindings:
        if b.analog is None and b.tok is None:
            F.append("block '%s' in the map has no '+' line: nothing triggers it" % b.action)

    # mouse (2, 4)
    M.mouse_rows = []
    for tok, name in (("LeftBtn", "Left button"), ("MiddleBtn", "Middle button"), ("RightBtn", "Right button")):
        acts = M.by_key.get(("mouse", tok.lower()), [])
        M.mouse_rows.append((name, " + ".join(label(M, a) for a in acts) if acts else "not bound", "", True))
    md = M.data["mouse"]
    for xb in ("XButton1", "XButton2"):
        key = M.remap["xbuttons"].get(xb)
        if key is None:
            F.append("i76-remap.ahk has no '%s::' line but controls-sheet.json lists it under mouse" % xb)
            continue
        text, ok = resolve(M, "mouse", xb, key, md[xb]["expect"])
        M.mouse_rows.append((md[xb]["name"], text, "key " + pretty(ahk_key(key)[1]), ok))
    for extra in sorted(set(M.remap["xbuttons"]) - {"XButton1", "XButton2"}):
        F.append("i76-remap.ahk remaps %s, which controls-sheet.json does not list under mouse" % extra)
    for w in ("WheelUp", "WheelDown"):
        key = M.play.get(w)
        if not key:
            F.append("PLAY-i76.ps1: default of -%s not found" % w)
            continue
        text, ok = resolve(M, "mouse", w, key, md[w]["expect"])
        M.mouse_rows.append((md[w]["name"], text, "key " + pretty(ahk_key(key)[1]), ok))

    # gamepad (2, 4)
    gp = M.data["gamepad"]
    used_at, claimed = set(), set()
    M.pad = {}                    # control -> {"base": [...], "shift": [...]}
    for e in gp["entries"]:
        at = e["at"]
        used_at.add(at)
        line = M.remap["pad_lines"].get(at)
        if line is None:
            F.append("gamepad entry '%s': i76-remap.ahk has no '@pad %s:' line" % (e["control"], at))
            line = ""
        if len(e["sends"]) != len(e["expect"]):
            F.append("gamepad entry at '%s': 'sends' and 'expect' differ in length" % at)
            continue
        at_sent = {ahk_key(k) for e2 in gp["entries"] if e2["at"] == at for k in e2["sends"]}
        for hint in re.findall(r"\(([A-Z]|[-=]|Esc)\)", line):
            if ahk_key(hint if len(hint) > 1 else hint.lower()) not in at_sent:
                F.append("gamepad '@pad %s' names key (%s) but the controls-sheet.json entries for it send %s" % (at, hint, e["sends"]))
        parts, ok_all = [], True
        for k, exp in zip(e["sends"], e["expect"]):
            if k not in M.remap["pad_keys"]:
                F.append("gamepad entry at '%s' says it sends '%s', but the XIPoll code in i76-remap.ahk never sends that key" % (at, k))
            claimed.add(k)
            text, ok = resolve(M, "gamepad", at, k, exp)
            ok_all = ok_all and ok
            if text not in parts:
                parts.append(text)
        text = e.get("label") or " + ".join(parts)
        keys = " ".join(pretty(ahk_key(k)[1]) for k in e["sends"])
        M.pad.setdefault(e["control"], {"base": [], "shift": []})[e["layer"]].append(
            {"text": text, "how": e.get("how", ""), "keys": keys, "ok": ok_all})
    for at in sorted(set(M.remap["pad_lines"]) - used_at):
        F.append("i76-remap.ahk has '@pad %s: %s' but controls-sheet.json has no gamepad entry for it" % (at, M.remap["pad_lines"][at]))
    for k in sorted(M.remap["pad_keys"] - claimed):
        F.append("the XIPoll code in i76-remap.ahk sends '%s', which no gamepad entry in controls-sheet.json claims" % k)
    # native pad bindings in the map
    M.native_joy = [b for b in M.bindings if (b.analog and b.analog[0].startswith("joystick")) or (b.dev or "").startswith("joystick")]
    for b in M.native_joy:
        if not b.analog:
            F.append("the map binds %s %s natively to '%s'; the sheet's gamepad / wheel pages assume the layers own every button (docs/WHEEL-T300.md: a native binding beside the layer fires twice)" % (b.dev, b.tok, b.action))

    # wheel (2, 4)
    wd = M.data["wheel"]
    base, alt, hold = M.remap["gWheelBase"], M.remap["gWheelAlt"], M.remap["gWheelHoldSet"]
    nums = set(base) | set(alt) | ({M.remap["shift_btn"]} if M.remap["shift_btn"] else set())
    for n in sorted(nums - set(wd["buttons"]), key=int):
        F.append("i76-remap.ahk has wheel button %s; controls-sheet.json wheel.buttons has no entry for it" % n)
    for n in sorted(set(wd["buttons"]) - nums, key=int):
        F.append("controls-sheet.json wheel.buttons lists button %s; i76-remap.ahk's gWheelBase / gWheelAlt do not" % n)
    M.wheel_rows = []
    for n in sorted(set(wd["buttons"]) & nums, key=int):
        d = wd["buttons"][n]
        if n == M.remap["shift_btn"]:
            if d["base"] != "SHIFT":
                F.append("wheel button %s is gWheelShiftBtn in i76-remap.ahk; controls-sheet.json says base '%s'" % (n, d["base"]))
            M.wheel_rows.append((n, d["name"], ("SHIFT (hold)", "", True), ("", "", True)))
            continue
        cells = []
        for layer, table in (("base", base), ("shift", alt)):
            key = table.get(n)
            if key is None:
                if d.get(layer):
                    F.append("wheel button %s %s: controls-sheet.json expects '%s' but the .ahk table has no key" % (n, layer, d[layer]))
                cells.append(("", "", True))
                continue
            text, ok = resolve(M, "wheel", "%s%s" % ("" if layer == "base" else "shift+", n), key, d.get(layer))
            cells.append((text, pretty(ahk_key(key)[1]), ok))
        M.wheel_rows.append((n, d["name"], cells[0], cells[1]))
    M.wheel_hat = []
    for ang in ("0", "9000", "18000", "27000"):
        d = wd["hat"][ang]
        cells = []
        for layer, table in (("base", M.remap["gWheelHat"]), ("shift", M.remap["gWheelHatAlt"])):
            key = table.get(ang)
            if key is None:
                if d.get(layer):
                    F.append("wheel hat %s %s: controls-sheet.json expects '%s' but the .ahk table has no key" % (d["name"], layer, d[layer]))
                cells.append(("", "", True))
                continue
            if not d.get(layer):
                F.append("wheel hat %s %s: the .ahk sends '%s' but controls-sheet.json expects nothing" % (d["name"], layer, key))
            text, ok = resolve(M, "wheel", "%shat-%s" % ("" if layer == "base" else "shift+", ang), key, d.get(layer))
            cells.append((text, pretty(ahk_key(key)[1]), ok))
        M.wheel_hat.append((d["name"], cells[0], cells[1]))

    # stick (2, 4): the script's own tables carry the action; it must be what the map binds the key to
    def stick_cell(kind, e):
        text, ok = resolve(M, "stick", "%s %s" % (kind, e.get("ctl", "")), e["key"], e["act"])
        return {"ctl": e.get("ctl", ""), "text": text, "key": pretty(ahk_key(e["key"])[1]), "ok": ok, "mode": e.get("mode", "")}
    M.stick_btn = {n: stick_cell("button", e) for n, e in M.stick["btn"].items()}
    M.stick_pov = [stick_cell("POV", e) for e in M.stick["pov"]]
    M.stick_axis = [stick_cell("axis", e) for e in M.stick["axis"]]
    sd = M.data["stick"]
    drawn = set(sd["grip_buttons"]) | {b for h in sd["hats"] for b in h["buttons"]}
    for n in sorted(set(M.stick["btn"]) - drawn):
        F.append("i76-ch-fighterstick.ahk has BTN[%d]; controls-sheet.json stick.hats / grip_buttons does not place it on the page" % n)
    for n in sorted(drawn - set(M.stick["btn"])):
        F.append("controls-sheet.json places stick button %d on the page; i76-ch-fighterstick.ahk has no BTN[%d]" % (n, n))

    # 5. the known-mismatch list must stay true
    for mid in sorted(set(M.known) - set(M.mismatches)):
        F.append("known_mismatches lists '%s' but the checker no longer finds it: remove the entry" % mid)
    return F


# ----------------------------------------------------------------------------- text helpers
PRETTY = {"One": "1", "Two": "2", "Three": "3", "Four": "4", "Five": "5", "Six": "6", "Seven": "7",
          "Eight": "8", "Nine": "9", "Zero": "0", "Comma": ", (comma)", "Period": ". (period)",
          "Minus": "- (minus)", "Equal": "= (equals)", "LeftBracket": "[", "RightBracket": "]",
          "SemiColon": "; (semicolon)", "Quote": "' (quote)",
          "GreyUpArrow": "Up arrow", "GreyDownArrow": "Down arrow", "GreyLeftArrow": "Left arrow",
          "GreyRightArrow": "Right arrow", "GreyPageUp": "Page Up", "GreyPageDown": "Page Down",
          "GreyEnd": "End", "UpArrow": "Up arrow (plain set)", "DownArrow": "Down arrow (plain set)",
          "LeftArrow": "Left arrow (plain set)", "RightArrow": "Right arrow (plain set)",
          "LeftBtn": "Left mouse button", "RightBtn": "Right mouse button", "MiddleBtn": "Middle mouse button",
          "Left/Right": "left / right axis", "Down/Up": "forward / back axis"}


def pretty(tok):
    return PRETTY.get(tok, tok)


def chord_text(tok, mods=frozenset(), dev="keyboard"):
    # tok may arrive lower-cased (from a chord tuple): recover the display form
    for k in PRETTY:
        if k.lower() == tok.lower():
            tok = k
            break
    else:
        if len(tok) == 1:
            tok = tok.upper()
    t = pretty(tok)
    return " + ".join([m.capitalize() if m != "control" else "Ctrl" for m in sorted(mods)] + [t])


def keys_of(bindings, action_set):
    """All triggers of a set of actions, as display strings, in file order, de-duplicated."""
    out = []
    for b in bindings:
        if b.action not in action_set:
            continue
        if b.analog:
            dev = "Joystick 1" if b.analog[0] == "joystick1" else b.analog[0]
            t = "%s, %s" % (dev, pretty(b.analog[1]))
        elif b.tok:
            t = chord_text(b.tok, b.mods, b.dev)
        else:
            continue
        if t not in out:
            out.append(t)
    return out


def compare_rows(M):
    """[(group id, label, stock keys, our keys, changed)] one row per distinct label."""
    rows, seen = [], set()
    order = list(M.actions) + list(M.stock_only)
    for a in order:
        meta = M.actions.get(a) or M.stock_only[a]
        lab = meta["label"]
        if lab in seen:
            continue
        seen.add(lab)
        same = {x for x in order if (M.actions.get(x) or M.stock_only[x])["label"] == lab}
        s = keys_of(M.stock_bindings, same)
        o = keys_of(M.bindings, same)
        rows.append((meta["group"], lab, s, o, s != o))
    return rows


def md_table(M):
    L = [MD_BEGIN, "",
         "| Action | 1997 keys (GOG 2.1.0.17) | This project's map | |",
         "|---|---|---|---|"]
    def cell(keys):
        return "<br>".join("`%s`" % k for k in keys) if keys else "not bound"
    for gid in [g["id"] for g in M.data["groups"]]:
        for g, lab, s, o, changed in compare_rows(M):
            if g == gid:
                L.append("| %s | %s | %s | %s |" % (lab, cell(s), cell(o), "changed" if changed else ""))
    L += ["",
          "Generated from `controls/input.map` (md5 `%s`) and `tools/controls-sheet/stock-2.1.0.17.json` "
          "(GOG's map, md5 `%s`). \"plain set\" = the engine's `UpArrow` / `DownArrow` / `LeftArrow` / "
          "`RightArrow` tokens, as opposed to the `Grey*` set that the dedicated arrow keys send." % (M.map_md5, M.stock["md5"]),
          "", MD_END]
    return "\n".join(L)


def controls_md_state(M):
    """(current text, wanted text) of docs/CONTROLS.md with the generated block refreshed."""
    cur = read(CONTROLS_MD)
    a, b = cur.find(MD_BEGIN), cur.find(MD_END)
    if a < 0 or b < 0:
        return cur, None
    return cur, cur[:a] + md_table(M) + cur[b + len(MD_END):]


# ----------------------------------------------------------------------------- HTML
def esc(s):
    return html.escape(str(s), quote=True)


# The physical keyboard (ANSI, no numeric keypad: this map binds nothing there).
# (legend, map token or None, width in key units). A token starting with '!' is a fixed engine key.
KB_ROWS = [
    [("Esc", "!Esc", 1), (None, None, 1), ("F1", "!F1", 1), ("F2", "!F2", 1), ("F3", "!F3", 1), ("F4", None, 1),
     (None, None, .5), ("F5", None, 1), ("F6", None, 1), ("F7", "!F7", 1), ("F8", "!F8", 1),
     (None, None, .5), ("F9", "!F9", 1), ("F10", "!F10", 1), ("F11", None, 1), ("F12", None, 1),
     (None, None, .4), ("PrtSc", None, 1), ("ScrLk", None, 1), ("Pause", None, 1)],
    [("`", None, 1), ("1", "One", 1), ("2", "Two", 1), ("3", "Three", 1), ("4", "Four", 1), ("5", "Five", 1),
     ("6", "Six", 1), ("7", "Seven", 1), ("8", "Eight", 1), ("9", "Nine", 1), ("0", "Zero", 1),
     ("-", "Minus", 1), ("=", "Equal", 1), ("Backspace", None, 2),
     (None, None, .4), ("Ins", "Insert", 1), ("Home", None, 1), ("PgUp", "GreyPageUp", 1)],
    [("Tab", "Tab", 1.5), ("Q", "Q", 1), ("W", "W", 1), ("E", "E", 1), ("R", "R", 1), ("T", "T", 1), ("Y", "Y", 1),
     ("U", "U", 1), ("I", "I", 1), ("O", "O", 1), ("P", "P", 1), ("[", "LeftBracket", 1), ("]", "RightBracket", 1),
     ("\\", None, 1.5),
     (None, None, .4), ("Del", None, 1), ("End", "GreyEnd", 1), ("PgDn", "GreyPageDown", 1)],
    [("Caps", None, 1.75), ("A", "A", 1), ("S", "S", 1), ("D", "D", 1), ("F", "F", 1), ("G", "G", 1), ("H", "H", 1),
     ("J", "J", 1), ("K", "K", 1), ("L", "L", 1), (";", "SemiColon", 1), ("'", "Quote", 1), ("Enter", "Enter", 2.25)],
    [("Shift", None, 2.25), ("Z", "Z", 1), ("X", "X", 1), ("C", "C", 1), ("V", "V", 1), ("B", "B", 1), ("N", "N", 1),
     ("M", "M", 1), (",", "Comma", 1), (".", "Period", 1), ("/", None, 1), ("Shift", None, 2.75),
     (None, None, 1.4), ("↑", "GreyUpArrow", 1)],
    [("Ctrl", None, 1.25), ("Win", None, 1.25), ("Alt", None, 1.25), ("Space", "Space", 6.25), ("Alt", None, 1.25),
     ("Win", None, 1.25), ("Menu", None, 1.25), ("Ctrl", None, 1.25),
     (None, None, .4), ("←", "GreyLeftArrow", 1), ("↓", "GreyDownArrow", 1), ("→", "GreyRightArrow", 1)],
]


def wrap(text, width):
    lines, cur = [], ""
    for w in text.split():
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = (cur + " " + w).strip()
    if cur:
        lines.append(cur)
    return lines


def keyboard_svg(M):
    P, H, GAP, FGAP = 52.0, 50.0, 3.0, 9.0
    out = []
    y = 0.0
    width = 0.0
    for r, row in enumerate(KB_ROWS):
        x = 0.0
        for legend, tok, w in row:
            kw = w * P
            if legend is None:
                x += kw
                continue
            meta = None
            if tok and tok.startswith("!"):
                meta = M.fixed.get(tok[1:])
                short = meta["key"] if meta else None
            elif tok:
                acts = M.by_key.get(("keyboard", tok.lower()), [])
                if acts:
                    meta = M.actions[acts[0]]
                    short = " / ".join(dict.fromkeys(M.actions[a]["key"] for a in acts))
            g = M.groups[meta["group"]] if meta else None
            fill = g["color"] if g else "#ffffff"
            out.append('<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" rx="5" fill="%s" stroke="%s" stroke-width="%s"/>' % (
                x + GAP / 2, y + GAP / 2, kw - GAP, H - GAP, fill, "#222" if g else "#aaa", "1.3" if g else "0.8"))
            out.append('<text x="%.1f" y="%.1f" class="%s">%s</text>' % (x + 6, y + 14, "kl" if g else "kl un", esc(legend)))
            if g:
                out.append('<text x="%.1f" y="%.1f" class="kc">%s</text>' % (x + kw - 6, y + 14, esc(g["code"])))
                lines = wrap(short, max(9, int((kw - 8) / 5.2)))[:3]
                y0 = y + 29 + (10 if len(lines) == 1 else 5 if len(lines) == 2 else 0) - (2 if len(lines) == 3 else 0)
                for i, ln in enumerate(lines):
                    out.append('<text x="%.1f" y="%.1f" class="ka" text-anchor="middle">%s</text>' % (x + kw / 2, y0 + i * 9.6, esc(ln)))
            x += kw
        width = max(width, x)
        y += H + (FGAP if r == 0 else 0)
    return '<svg class="kb" viewBox="0 0 %.0f %.0f" xmlns="http://www.w3.org/2000/svg">%s</svg>' % (width, y, "".join(out))


def group_lists(M):
    cols = []
    for g in M.data["groups"]:
        rows, seen = [], set()
        for a, meta in M.actions.items():
            if meta["group"] != g["id"] or meta["label"] in seen:
                continue
            seen.add(meta["label"])
            same = {x for x, m2 in M.actions.items() if m2["label"] == meta["label"]}
            keys = [k for k in keys_of(M.bindings, same) if "mouse button" not in k]
            if keys:
                rows.append((meta["label"], keys))
        for k, meta in M.fixed.items():
            if meta["group"] == g["id"] and meta["label"] not in seen:
                seen.add(meta["label"])
                rows.append((meta["label"], [x for x, m2 in M.fixed.items() if m2["label"] == meta["label"]]))
        def kbds(keys):
            keys = [short_key(k) for k in keys]
            if len(keys) > 2 and all(k.startswith("Shift + ") for k in keys):
                rest = [k[8:] for k in keys]                                # one chip for the four Shift + arrow chords
                keys = ["Shift + " + ("arrows" if set(rest) == {"Up", "Down", "Left", "Right"} else " / ".join(rest))]
            return " ".join("<kbd>%s</kbd>" % esc(k) for k in keys)
        body = "".join('<tr><td class="l">%s</td><td class="k">%s</td></tr>' % (esc(lab), kbds(keys)) for lab, keys in rows)
        cols.append('<div class="grp"><h3><span class="sw" style="background:%s">%s</span>%s</h3><table>%s</table></div>' % (
            g["color"], esc(g["code"]), esc(g["label"]), body))
    return "".join(cols)


def short_key(k):
    return (k.replace(" (comma)", "").replace(" (period)", "").replace(" (semicolon)", "").replace(" (quote)", "")
             .replace(" (minus)", "").replace(" (equals)", "").replace("Joystick 1, left / right axis", "Joystick 1 X").replace("Joystick 1, forward / back axis", "Joystick 1 Y")
             .replace("Page Up", "PgUp").replace("Page Down", "PgDn").replace(" arrow", ""))


def dag(ok):
    return "" if ok else '<sup class="dag">&dagger;</sup>'


def mouse_block(M):
    rows = "".join('<tr><td class="mn">%s</td><td>%s%s</td><td class="k">%s</td></tr>' % (
        esc(n), esc(t), dag(ok), ('<kbd>%s</kbd>' % esc(short_key(k[4:]))) if k else "") for n, t, k, ok in M.mouse_rows)
    svg = ('<svg class="mouse" viewBox="0 0 80 112" xmlns="http://www.w3.org/2000/svg">'
           '<rect x="8" y="4" width="68" height="104" rx="32" fill="#fff" stroke="#222" stroke-width="2"/>'
           '<line x1="8" y1="48" x2="76" y2="48" stroke="#222" stroke-width="1.5"/><line x1="42" y1="4" x2="42" y2="48" stroke="#222" stroke-width="1.5"/>'
           '<rect x="35" y="14" width="14" height="26" rx="7" fill="#ccc" stroke="#222" stroke-width="1.5"/>'
           '<text x="23" y="34" class="mt">L</text><text x="62" y="34" class="mt">R</text>'
           '<rect x="2" y="54" width="8" height="15" rx="2" fill="#ccc" stroke="#222"/><rect x="2" y="72" width="8" height="15" rx="2" fill="#ccc" stroke="#222"/>'
           '<text x="16" y="66" class="mt s">5</text><text x="16" y="84" class="mt s">4</text></svg>')
    return '<div class="grp mousegrp"><h3>Mouse</h3><div class="mrow">%s<table>%s</table></div></div>' % (svg, rows)


def status_block(M, *keys):
    items = [s for k in keys for s in M.data["status"][k]]
    return '<div class="status"><b>Status.</b> %s</div>' % " ".join(esc(s) for s in items)


def page(M, n, total, title, body, cls=""):
    foot = ("i76-everywhere &middot; controls/input.map md5 %s &middot; generated %s &middot; page %d of %d &middot; "
            "regenerate: tools\\controls-sheet\\build.ps1" % (M.map_md5, M.today, n, total))
    return ('<section class="page %s"><header><h1>%s</h1><p>%s</p></header>%s<footer>%s</footer></section>'
            % (cls, esc(title), esc(M.data["subtitle"]), body, foot))


PAD_SVG = '''<svg class="pad" viewBox="228 40 444 286" xmlns="http://www.w3.org/2000/svg">
<path d="M300,110 h300 a55,55 0 0 1 55,55 l18,110 a45,45 0 0 1 -80,32 l-30,-52 h-226 l-30,52 a45,45 0 0 1 -80,-32 l18,-110 a55,55 0 0 1 55,-55 z" fill="#f4f4f4" stroke="#222" stroke-width="2"/>
<rect x="290" y="84" width="92" height="20" rx="8" class="pp"/><text x="336" y="98" class="pt">LB</text>
<rect x="518" y="84" width="92" height="20" rx="8" class="pp"/><text x="564" y="98" class="pt">RB</text>
<rect x="300" y="50" width="66" height="26" rx="9" class="pp"/><text x="333" y="68" class="pt">LT</text>
<rect x="534" y="50" width="66" height="26" rx="9" class="pp"/><text x="567" y="68" class="pt">RT</text>
<circle cx="330" cy="172" r="30" class="pp"/><circle cx="330" cy="172" r="19" class="ps"/><text x="330" y="177" class="pt">LS</text>
<circle cx="505" cy="250" r="30" class="pp"/><circle cx="505" cy="250" r="19" class="ps"/><text x="505" y="255" class="pt">RS</text>
<path d="M383,222 h24 v20 h20 v24 h-20 v20 h-24 v-20 h-20 v-24 h20 z" class="pp"/><text x="395" y="258" class="pt sm">D-pad</text>
<circle cx="565" cy="140" r="15" class="pp"/><text x="565" y="145" class="pt">Y</text>
<circle cx="533" cy="172" r="15" class="pp"/><text x="533" y="177" class="pt">X</text>
<circle cx="597" cy="172" r="15" class="pp"/><text x="597" y="177" class="pt">B</text>
<circle cx="565" cy="204" r="15" class="pp"/><text x="565" y="209" class="pt">A</text>
<rect x="398" y="140" width="40" height="16" rx="8" class="pp"/><text x="418" y="152" class="pt sm">Back</text>
<rect x="462" y="140" width="40" height="16" rx="8" class="pp"/><text x="482" y="152" class="pt sm">Start</text>
</svg>'''


def pad_box(M, control, title=None):
    d = M.pad.get(control, {"base": [], "shift": []})
    def lines(items):
        return "".join('<div class="pl">%s%s%s <span class="kk">%s</span></div>' % (
            esc(i["text"]), dag(i["ok"]), (' <i>(%s)</i>' % esc(i["how"])) if i["how"] else "", esc(short_key(i["keys"]))) for i in items)
    unb = M.data["gamepad"]["unbound_controls"].get(control)
    native = ""
    if control == "LS":
        nat = [b for b in M.native_joy if b.analog]
        native = "".join('<div class="pl">%s <span class="kk">native: %s %s</span></div>' % (
            esc(label(M, b.action)), esc(b.analog[0]), esc(b.analog[1])) for b in nat)
    base = native + lines(d["base"])
    if not base:
        base = '<div class="pl un">%s</div>' % esc(unb or "not bound")
    shift = lines(d["shift"])
    return ('<div class="pbox"><div class="pname">%s</div><div class="pbase">%s</div>%s</div>' % (
        esc(title or control), base, ('<div class="pshift"><span class="lb">LB +</span>%s</div>' % shift) if shift else ""))


def gamepad_page(M):
    left = "".join(pad_box(M, c, t) for c, t in (
        ("LT", "LT (left trigger)"), ("LB", "LB (left bumper)"), ("LS", "LS (left stick)"), ("L3", "L3 (press left stick)"),
        ("D-pad up", None), ("D-pad down", None), ("D-pad left", None), ("D-pad right", None), ("Back", "Back / Select")))
    right = "".join(pad_box(M, c, t) for c, t in (
        ("RT", "RT (right trigger)"), ("RB", "RB (right bumper)"), ("Y", None), ("X", None), ("B", None), ("A", None),
        ("RS", "RS (right stick)"), ("R3", "R3 (press right stick)"), ("Start", None)))
    pad_mis = [w for i, w in M.mismatches.items() if i.startswith("gamepad:")]
    mis = ""
    if pad_mis:
        mis = '<div class="mis"><b>&dagger; Known mismatches</b> (left as the owner plays it):<ul>%s</ul></div>' % "".join(
            "<li>%s</li>" % esc(M.known.get(i, w)) for i, w in M.mismatches.items() if i.startswith("gamepad:"))
    mid = ('<div class="padmid">%s<p class="note"><b>Hold LB</b> for the shift layer (the <span class="lb">LB +</span> lines). '
           'Small grey text is the key the AutoHotkey layer types. The left stick is the only native binding: '
           'without the layer (i76-remap.ahk, started by PLAY-i76.bat) the buttons do nothing.</p>%s%s</div>' % (
               PAD_SVG, mis, status_block(M, "gamepad")))
    return '<div class="padgrid"><div class="pcol">%s</div>%s<div class="pcol">%s</div></div>' % (left, mid, right)


def cell(c):
    text, key, ok = c
    if not text:
        return "<td></td>"
    return '<td>%s%s%s</td>' % (esc(text), dag(ok), (' <span class="kk">%s</span>' % esc(short_key(key))) if key else "")


def cross(title, up, right, down, left, centre=""):
    def c(x):
        return '%s%s <span class="kk">%s</span>' % (esc(x["text"]), dag(x["ok"]), esc(short_key(x["key"])))
    return ('<div class="cross"><div class="ct">%s</div><div class="cg"><div class="cu">%s</div><div class="cl">%s</div>'
            '<div class="cc">%s</div><div class="cr">%s</div><div class="cd">%s</div></div></div>' % (
                esc(title), c(up), c(left), esc(centre), c(right), c(down)))


# Schematic front view of the T300RS rim (PS4 layout). Positions are drawn from the Thrustmaster layout, not
# measured; the badge is the PC button number from the manual's "MAPPING FOR PC" page (docs/WHEEL-T300.md).
# The four face buttons carry the numbers in the order the manual lists them (triangle, square, circle, cross = 3 to 6).
WHEEL_SPOTS = {  # PC button -> (x, y, legend, shape, badge dx, badge dy)
    "1": (150, 82, "L1", "paddle", -22, -2), "2": (290, 82, "R1", "paddle", 22, -2),
    "10": (100, 232, "L2", "round", -16, -10), "11": (146, 252, "L3", "round", -16, 8), "7": (176, 132, "SHARE", "pill", -28, 0),
    "9": (340, 232, "R2", "round", 16, -10), "12": (294, 252, "R3", "round", 16, 8), "8": (264, 132, "OPTIONS", "pill", 30, 0),
    "3": (318, 152, "△", "face", 0, -18), "4": (292, 178, "□", "face", -19, -10), "5": (344, 178, "○", "face", 19, -10), "6": (318, 204, "✕", "face", 0, 18),
    "13": (220, 268, "PS", "round", 18, -8),
}


def wheel_svg(M):
    o = ['<svg class="wheel" viewBox="20 20 400 352" xmlns="http://www.w3.org/2000/svg">',
         # the two shift paddles sit behind the rim, upper left and right of the hub
         '<path d="M118,64 h50 a8,8 0 0 1 8,8 v22 h-66 v-22 a8,8 0 0 1 8,-8 z" class="pp dash"/>',
         '<path d="M272,64 h50 a8,8 0 0 1 8,8 v22 h-66 v-22 a8,8 0 0 1 8,-8 z" class="pp dash"/>',
         '<circle cx="220" cy="185" r="150" fill="none" stroke="#222" stroke-width="26"/>',
         '<circle cx="220" cy="185" r="150" fill="none" stroke="#f4f4f4" stroke-width="22"/>',
         '<path d="M74,160 h292 a8,8 0 0 1 8,8 v46 a8,8 0 0 1 -8,8 h-70 l-30,74 h-92 l-30,-74 h-70 a8,8 0 0 1 -8,-8 v-46 a8,8 0 0 1 8,-8 z" fill="#f4f4f4" stroke="#222" stroke-width="2"/>',
         '<rect x="140" y="110" width="160" height="110" rx="26" fill="#f4f4f4" stroke="#222" stroke-width="2"/>',
         '<text x="220" y="196" class="pt sm">T300 RS</text>',
         # D-pad (POV hat) on the left spoke
         '<path d="M118,166 h18 v14 h14 v18 h-14 v14 h-18 v-14 h-14 v-18 h14 z" class="pp"/>',
         '<text x="127" y="192" class="pt xs">D-pad</text>']
    for n, (x, y, leg, shape, bdx, bdy) in WHEEL_SPOTS.items():
        if shape == "paddle":
            o.append('<text x="%d" y="%d" class="pt sm">%s paddle (behind)</text>' % (x - 7 if n == "1" else x + 7, y - 6, leg))
        elif shape == "pill":
            o.append('<rect x="%d" y="%d" width="40" height="14" rx="7" class="pp"/><text x="%d" y="%d" class="pt xs">%s</text>' % (x - 20, y - 7, x, y + 3, leg))
        elif shape == "face":
            o.append('<circle cx="%d" cy="%d" r="10" class="pp"/><text x="%d" y="%d" class="pt">%s</text>' % (x, y, x, y + 4.5, leg))
        else:
            o.append('<circle cx="%d" cy="%d" r="11" class="pp"/><text x="%d" y="%d" class="pt sm">%s</text>' % (x, y, x, y + 3, leg))
        bx, by = x + bdx, y + bdy
        if shape == "paddle":
            bx, by = (x - 50 if n == "1" else x + 50), y - 9
        o.append('<circle cx="%d" cy="%d" r="7.5" class="badge"/><text x="%d" y="%d" class="bt">%s</text>' % (bx, by, bx, by + 3.2, n))
    o.append('<text x="220" y="365" class="pt sm">pedals: throttle / brake &#183; rim: steer (native, no layer needed)</text></svg>')
    return "".join(o)


def wbox(M, num, title, b, s, hold=False):
    def line(c):
        text, key, ok = c
        return '%s%s <span class="kk">%s</span>' % (esc(text), dag(ok), esc(short_key(key)) if key else "")
    base = ('<div class="pl">%s%s</div>' % (line(b), ' <i>(hold)</i>' if hold else "")) if b[0] else '<div class="pl un">not bound</div>'
    shift = ('<div class="pshift"><span class="lb">%s +</span><span>%s</span></div>' % (esc(M.remap["shift_btn"]), line(s))) if s[0] else ""
    badge = '<span class="nb">%s</span>' % esc(num) if num else ""
    return '<div class="pbox"><div class="pname">%s%s</div><div class="pbase">%s</div>%s</div>' % (badge, esc(title), base, shift)


def wheel_page(M):
    wd = M.data["wheel"]
    rows = {n: (name, b, s) for n, name, b, s in M.wheel_rows}
    hold = set(M.remap["gWheelHoldSet"])
    def btn(n, title):
        name, b, s = rows[n]
        return wbox(M, n, title, b, s, n in hold)
    hat = {name: (b, s) for name, b, s in M.wheel_hat}
    left = btn("1", "L1 left paddle") + "".join(wbox(M, "", nm, *hat[nm]) for nm in ("D-pad up", "D-pad right", "D-pad down", "D-pad left")) + \
        btn("7", "SHARE (SE)") + btn("10", "L2") + btn("11", "L3")
    sb = M.remap["shift_btn"]
    right = btn("2", "R1 right paddle") + btn("3", "△ face button") + btn("4", "□ face button") + btn("5", "○ face button") + \
        btn(sb, "✕ face button: SHIFT (hold)") + btn("8", "OPTIONS") + btn("9", "R2") + btn("12", "R3") + btn("13", "PS")
    mid = ('<div class="padmid">%s<p class="note"><b>Hold button %s</b> (the lowest face button) for the shift layer: the '
           '<span class="lb">%s +</span> lines. Small grey text is the key i76-remap.ahk types; buttons with <i>(hold)</i> keep their key down while pressed, '
           'the rest tap once. Steering and pedals are native (input.map) and work without the layer.</p>'
           '<p class="note">The black badge is the PC button number (Thrustmaster manual). The picture is a schematic of the PS4-layout rim; '
           'the face-button numbers follow the order the manual lists them (△ □ ○ ✕ = 3 to 6) and have not been press-tested by symbol: '
           'if one is off, the numbers on the boxes are what counts.</p>%s</div>' % (wheel_svg(M), esc(sb), esc(sb), status_block(M, "wheel")))
    return '<div class="padgrid wheelgrid"><div class="pcol">%s</div>%s<div class="pcol">%s</div></div>' % (left, mid, right)


# Schematic CH Fighterstick grip, seen from the pilot's seat (front of the grip to the left). Positions approximate.
STICK_SVG = '''<svg class="stick" viewBox="0 0 300 400" xmlns="http://www.w3.org/2000/svg">
<ellipse cx="150" cy="370" rx="120" ry="20" fill="#e4e4e4" stroke="#222" stroke-width="2"/>
<rect x="138" y="300" width="24" height="70" fill="#ccc" stroke="#222" stroke-width="1.5"/>
<path d="M95,120 q-10,-70 55,-80 q70,-5 70,70 l-10,80 q-5,40 -10,110 h-70 q-5,-60 -20,-100 q-20,-40 -15,-80 z" fill="#f4f4f4" stroke="#222" stroke-width="2"/>
<circle cx="120" cy="70" r="15" class="pp"/><circle cx="120" cy="70" r="6" class="ps"/><text x="120" y="98" class="pt xs">cone (POV)</text>
<circle cx="185" cy="72" r="14" class="pp"/><path d="M175,72 h20 M185,62 v20" stroke="#222" stroke-width="1.2"/><text x="185" y="99" class="pt xs">convex 5-8</text>
<rect x="168" y="112" width="30" height="24" rx="4" class="pp"/><path d="M172,112 v-5 h6 v5 M180,112 v-5 h6 v5 M188,112 v-5 h6 v5" fill="none" stroke="#222"/><text x="183" y="149" class="pt xs">castle 9-12</text>
<circle cx="120" cy="128" r="12" class="pp"/><text x="120" y="152" class="pt xs">trim 13-16</text>
<rect x="148" y="38" width="22" height="12" rx="5" fill="#c33" stroke="#222"/><text x="159" y="31" class="pt xs">2 pickle</text>
<path d="M92,170 q-22,10 -18,40 l14,-2 q-2,-22 10,-30 z" fill="#ccc" stroke="#222" stroke-width="1.5"/><text x="58" y="196" class="pt xs">1 trigger</text>
<rect x="88" y="252" width="14" height="22" rx="4" fill="#c33" stroke="#222"/><text x="64" y="268" class="pt xs">4 pinky</text>
<rect x="212" y="150" width="12" height="22" rx="4" class="pp"/><text x="230" y="165" class="pt xs" text-anchor="start" style="text-anchor:start">3 MODE (back)</text>
<text x="150" y="395" class="pt xs">forward = reverse &#183; back = handbrake &#183; left / right = gear</text>
</svg>'''


def stick_page(M):
    sd = M.data["stick"]
    ax = {(a_["ctl"]): a_ for a_ in M.stick_axis}
    def find(prefix):
        for k, v in ax.items():
            if prefix in k.upper():
                return v
        return {"text": "", "key": "", "ok": True}
    gear = cross("Stick deflection: gearbox and handbrake", find("FORWARD"), find("RIGHT"), find("BACK"), find("LEFT"), "stick")
    pov = M.stick_pov
    cone = cross("Cone hat (POV): look, held", pov[0], pov[1], pov[2], pov[3], "cone")
    hats = []
    for h in sd["hats"]:
        b = [M.stick_btn[n] for n in h["buttons"]]
        hats.append(cross("%s (buttons %d to %d)" % (h["name"], h["buttons"][0], h["buttons"][-1]), b[0], b[1], b[2], b[3], "hat"))
    grip = "".join(wbox(M, str(n), M.stick_btn[n]["ctl"], (M.stick_btn[n]["text"], M.stick_btn[n]["key"], M.stick_btn[n]["ok"]), ("", "", True))
                   for n in sd["grip_buttons"])
    mid = ('<div class="padmid">%s<p class="note">All stick controls are typed by i76-ch-fighterstick.ahk. Forward = reverse only while held; '
           'back = handbrake while held; left / right = one gear per movement. Weapon link is on the keyboard (F) only. '
           'The picture is a schematic of the grip; hat and button names follow FIGHTERSTICK.md.</p>%s</div>' % (STICK_SVG, status_block(M, "stick")))
    left = cone + hats[0] + gear
    right = hats[1] + hats[2] + grip
    return '<div class="padgrid stickgrid"><div class="pcol">%s</div>%s<div class="pcol">%s</div></div>' % (left, mid, right)


def compare_page(M):
    rows = compare_rows(M)
    def tr(r):
        g, lab, s, o, ch = r
        def c(keys):
            return "<br>".join(esc(k) for k in keys) if keys else '<span class="un">not bound</span>'
        return '<tr class="%s"><td>%s</td><td>%s</td><td>%s</td><td class="ch">%s</td></tr>' % (
            "chg" if ch else "", esc(lab), c(s), c(o), "&#9679;" if ch else "")
    half = (len(rows) + 1) // 2
    def table(part):
        return ('<table class="cmp"><tr><th>Action</th><th>1997 keys</th><th>This project</th><th></th></tr>%s</table>'
                % "".join(tr(r) for r in part))
    n = sum(1 for r in rows if r[4])
    return ('<div class="cmpwrap"><p class="note"><b>&#9679; = changed</b> (%d of %d rows). Every letter, number and punctuation key is ignored while Shift or Ctrl is held, in both maps.</p>'
            '<div class="cmpgrid">%s%s</div>%s</div>' % (n, len(rows), table(rows[:half]), table(rows[half:]), status_block(M, "compare")))


CSS = '''
@page { size: 11in 8.5in; margin: 0.4in; }
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body { font: 9.5px/1.3 "Segoe UI", Arial, Helvetica, sans-serif; color: #000; background: #fff;
       -webkit-print-color-adjust: exact; print-color-adjust: exact; }
.page { width: 10.2in; height: 7.68in; position: relative; overflow: hidden; page-break-after: always; break-after: page; }
.page:last-child { page-break-after: auto; break-after: auto; }
header { display: flex; align-items: baseline; gap: 14px; border-bottom: 2px solid #000; padding-bottom: 3px; margin-bottom: 7px; }
header h1 { font-size: 17px; margin: 0; white-space: nowrap; }
header p { margin: 0; font-size: 9.5px; }
footer { position: absolute; left: 0; right: 0; bottom: 0; border-top: 1px solid #000; padding-top: 2px; font-size: 7.5px; color: #222; }
h2 { font-size: 13px; margin: 0 0 4px; }
h3 { font-size: 11px; margin: 0 0 2px; border-bottom: 1px solid #000; padding-bottom: 1px; }
table { border-collapse: collapse; width: 100%; }
td, th { padding: 1px 3px; vertical-align: top; text-align: left; }
kbd { font: 600 8.5px Consolas, "Courier New", monospace; border: 1px solid #333; border-radius: 3px; padding: 0 3px; background: #fff; white-space: nowrap; }
.kk { font: 8px Consolas, "Courier New", monospace; color: #444; white-space: nowrap; }
.un { color: #555; font-style: italic; }
.dag { font-weight: 700; }
.note { margin: 3px 0; font-size: 9px; }
.status { font-size: 8px; margin-top: 4px; border-left: 3px solid #000; padding-left: 5px; }
.mis { font-size: 8.5px; border: 1.5px solid #000; padding: 3px 6px; margin-top: 5px; }
.mis ul { margin: 2px 0 0; padding-left: 14px; }
/* page 1 */
svg.kb { width: 100%; height: auto; display: block; }
.kl { font: 700 10.5px "Segoe UI", Arial, sans-serif; fill: #000; }
.kl.un { font-weight: 400; fill: #777; font-style: normal; }
.kc { font: 700 7px "Segoe UI", Arial, sans-serif; fill: #000; text-anchor: end; }
.ka { font: 600 8.6px "Segoe UI", Arial, sans-serif; fill: #000; }
.lists { display: grid; grid-template-columns: 1.02fr 1fr 1fr 1.3fr 1.08fr 1.6fr; gap: 9px; margin-top: 7px; font-size: 8.6px; }
.grp td.k { text-align: right; white-space: nowrap; } .grp td.l { width: 99%; }
.grp td { padding: 0.5px 1px; }
.sw { display: inline-block; width: 13px; text-align: center; border: 1px solid #000; margin-right: 4px; font-size: 8.5px; }
.mrow { display: flex; gap: 4px; align-items: flex-start; }
svg.mouse { width: 40px; flex: none; margin-top: 2px; }
.mt { font: 700 15px Arial; text-anchor: middle; } .mt.s { font-size: 12px; }
td.mn { font-weight: 600; white-space: nowrap; padding-right: 5px; }
/* page 2 */
.padgrid { display: grid; grid-template-columns: 1fr 3.55in 1fr; gap: 10px; }
.pcol { display: flex; flex-direction: column; gap: 4px; }
.pbox { border: 1px solid #000; border-radius: 4px; padding: 2px 6px 3px; }
.pname { font-weight: 700; font-size: 10.5px; }
.pl { font-size: 9.3px; }
.pshift { border-top: 1px dashed #666; margin-top: 2px; padding-top: 1px; display: flex; gap: 5px; }
.lb { font-weight: 700; font-size: 8.5px; border: 1px solid #000; border-radius: 3px; padding: 0 3px; white-space: nowrap; align-self: flex-start; background: #e4e4e4; }
svg.pad { width: 100%; height: auto; }
.pp { fill: #dcdcdc; stroke: #222; stroke-width: 1.2; } .ps { fill: #fff; stroke: #222; }
.pt { font: 700 12px Arial; text-anchor: middle; fill: #000; } .pt.sm { font: 600 7.4px Arial; }
/* pages 3 and 4: wheel and stick */
svg.wheel, svg.stick { width: 100%; height: auto; }
svg.stick { max-height: 4.3in; }
.pt.xs { font: 600 7px Arial; } .pp.dash { stroke-dasharray: 4 2; }
.badge { fill: #000; } .bt { font: 700 8.5px Arial; fill: #fff; text-anchor: middle; }
.nb { display: inline-block; min-width: 15px; text-align: center; background: #000; color: #fff; border-radius: 8px; font-size: 8.5px; margin-right: 5px; padding: 0 3px; }
.wheelgrid .pbox { padding-top: 1px; padding-bottom: 2px; } .wheelgrid .pcol { gap: 3px; }
.stickgrid { grid-template-columns: 1fr 3.1in 1fr; }
.stickgrid .pcol { gap: 6px; }
.cross { border: 1px solid #000; border-radius: 4px; padding: 3px 5px 5px; }
.ct { font-weight: 700; font-size: 9.6px; margin-bottom: 3px; }
.cg { display: grid; grid-template-columns: 1fr auto 1fr; grid-template-rows: auto auto auto; gap: 3px 5px; align-items: center; font-size: 9px; }
.cu { grid-column: 1 / 4; text-align: center; } .cd { grid-column: 1 / 4; text-align: center; }
.cl { text-align: right; } .cr { text-align: left; }
.cc { border: 1.5px solid #000; border-radius: 50%; width: 34px; height: 34px; display: flex; align-items: center; justify-content: center; font-size: 7.5px; background: #e4e4e4; }
.cu::before { content: "\\25B2  "; font-size: 7px; } .cd::before { content: "\\25BC  "; font-size: 7px; }
.cl::before { content: "\\25C0  "; font-size: 7px; } .cr::before { content: "\\25B6  "; font-size: 7px; }
/* page 4 */
.cmpgrid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
.cmp td, .cmp th { border-bottom: 1px solid #999; font-size: 9px; padding: 1.5px 4px; }
.cmp th { border-bottom: 1.5px solid #000; }
.cmp tr.chg td { font-weight: 600; background: #eee; }
.cmp td.ch { width: 12px; text-align: center; }
.p2 .padgrid { zoom: 1.2; } .p3 .padgrid { zoom: 1.12; } .p3s .padgrid { zoom: 1.2; } .p4 .cmpwrap { zoom: 1.33; }
@media screen { body { background: #777; } .page { background: #fff; margin: 12px auto; padding: 0; box-shadow: 0 0 8px #000; outline: 0.4in solid #fff; margin-top: 0.6in; margin-bottom: 0.9in; } }
'''


def build_html(M):
    p1 = ('%s<p class="note">Key colour and corner letter = group. Shift + arrow keys move the outside camera and the map. '
          'Keys with no label are not bound. F-keys and Esc are engine keys, not in input.map.</p>'
          '<div class="lists">%s%s</div>%s' % (keyboard_svg(M), group_lists(M), mouse_block(M), status_block(M, "keyboard", "mouse")))
    pages = [("Keyboard and mouse", p1, "p1"), ("Gamepad (Xbox layout)", gamepad_page(M), "p2"),
             ("Wheel: " + M.data["wheel"]["device"], wheel_page(M), "p3"),
             ("Flight stick: " + M.data["stick"]["device"], stick_page(M), "p3s"),
             ("Stock 1997 keys vs ours", compare_page(M), "p4")]
    body = "".join(page(M, i + 1, len(pages), "Interstate '76: " + t, b, c) for i, (t, b, c) in enumerate(pages))
    return ('<!doctype html><html lang="en"><head><meta charset="utf-8"><title>%s</title><style>%s</style></head><body>%s</body></html>\n'
            % (esc(M.data["title"]), CSS, body))


# ----------------------------------------------------------------------------- main
def extract_stock(path):
    raw = open(path, "rb").read()
    blocks = parse_map_text(raw.decode("latin-1").replace("\r\n", "\n"))
    out = {"_readme": "Bindings of GOG's own input.map (offline installer 2.1.0.17), as facts: action, sign, device, token per block. "
                      "Written by build_sheet.py --extract-stock; used for the 'stock vs ours' page and the table in docs/CONTROLS.md. "
                      "The game file itself is not in this repo.",
           "source": "input.map from setup_interstate76_2.1.0.17 (GOG offline installer), before any setup script touched it",
           "md5": hashlib.md5(raw).hexdigest(), "blocks": blocks}
    with open(STOCK, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, indent=1)
        f.write("\n")
    print("wrote %s (%d blocks, md5 %s)" % (STOCK, len(blocks), out["md5"]))


def main(argv):
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(errors="replace")
        except Exception:
            pass
    if len(argv) >= 2 and argv[0] == "--extract-stock":
        extract_stock(argv[1])
        return 0
    check_only = "--check" in argv
    M = load()
    M.today = datetime.date.today().isoformat()
    for a in argv:
        if a.startswith("--date="):
            M.today = a[7:]
    findings = check(M)
    cur, want = controls_md_state(M)
    if want is None:
        findings.append("docs/CONTROLS.md has no generated block (markers '%s' ... '%s')" % (MD_BEGIN, MD_END))
    elif check_only and cur != want:
        findings.append("docs/CONTROLS.md: the generated stock-vs-ours table is out of date. Run tools\\controls-sheet\\build.ps1")
    if findings:
        print("controls-sheet: %d finding(s). Nothing was written." % len(findings))
        for f in findings:
            print("  - " + f)
        return 1
    print("controls-sheet: sources agree (map md5 %s, %d actions, %d known mismatch(es) listed)" % (
        M.map_md5, len({b.action for b in M.bindings}), len(M.mismatches)))
    for mid, what in M.mismatches.items():
        print("  known mismatch: " + M.known[mid])
    if check_only:
        return 0
    with open(OUT_HTML, "w", encoding="utf-8", newline="\n") as f:
        f.write(build_html(M))
    print("wrote " + OUT_HTML)
    if cur != want:
        raw = open(CONTROLS_MD, "rb").read()
        nl = "\r\n" if b"\r\n" in raw else "\n"
        with open(CONTROLS_MD, "w", encoding="utf-8", newline="") as f:
            f.write(want.replace("\n", nl))
        print("refreshed the generated table in docs/CONTROLS.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
