
Version                              = 0x287

[General]
OutputAPI                            = d3d11_fl10_1
FullScreenMode                      = false
ScalingMode                          = stretched_ar
KeepWindowAspectRatio                = false
CaptureMouse                         = false
CenterAppWindow                      = false

[GeneralExt]
FPSLimit                             = 0
Resampling                           = bilinear
FullscreenAttributes                 = fake
WindowedAttributes                   = borderless
FreeMouse                            = false

[Glide]
VideoCard                           = voodoo_graphics
OnboardRAM                          = 4
MemorySizeOfTMU                     = 2048
NumberOfTMUs                        = 1
TMUFiltering                        = bilinear
Resolution                          = 3840x2880
Antialiasing                        = 4x
EnableGlideGammaRamp                = true
ForceEmulatingTruePCIAccess         = true
ForceVerticalSync                   = false
3DfxWatermark                       = false
3DfxSplashScreen                    = false
EnableInactiveAppState              = true

[GlideExt]
DitheringEffect                     = pure32bit
Dithering                           = forcealways
DitherOrderedMatrixSizeScale        = 0

[DirectX]
VideoCard                           = internal3D
VRAM                                = 256
Resolution                          = 1920x1440
dgVoodooWatermark                   = false
AppControlledScreenMode             = false
DisableAltEnterToToggleScreenMode   = false
