; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30158.0 

	TITLE	C:\Users\james\i76-map\tools\env-check\cl-hello\hello.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	_fma_leaf
PUBLIC	_main
PUBLIC	??_C@_0BB@CDJFNODP@hello?532?9bit?5?$CFg?6@	; `string'
PUBLIC	__real@3fc00000
PUBLIC	__real@3ff0000000000000
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	__fltused:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT __real@3ff0000000000000
CONST	SEGMENT
__real@3ff0000000000000 DQ 03ff0000000000000r	; 1
CONST	ENDS
;	COMDAT __real@3fc00000
CONST	SEGMENT
__real@3fc00000 DD 03fc00000r			; 1.5
CONST	ENDS
;	COMDAT ??_C@_0BB@CDJFNODP@hello?532?9bit?5?$CFg?6@
CONST	SEGMENT
??_C@_0BB@CDJFNODP@hello?532?9bit?5?$CFg?6@ DB 'hello 32-bit %g', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	0aH
	DB	0eH
voltbl	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\james\i76-map\tools\env-check\cl-hello\hello.c
;	COMDAT _main
_TEXT	SEGMENT
tv142 = -4						; size = 4
_a$ = -4						; size = 4
_x$ = -4						; size = 4
_main	PROC						; COMDAT

; 4    : int main(void) { volatile float x = 1.5f; printf("hello 32-bit %g\n", fma_leaf(x, 2.0f)); return 0; }

	push	ecx
	fld	DWORD PTR __real@3fc00000
	sub	esp, 8
	fstp	DWORD PTR _x$[esp+12]
	fld	DWORD PTR _x$[esp+12]
	fstp	DWORD PTR _a$[esp+12]

; 3    : float __cdecl fma_leaf(float a, float b) { return a * b + 1.0f; }

	fld	DWORD PTR _a$[esp+12]
	fadd	ST(0), ST(0)
	fadd	QWORD PTR __real@3ff0000000000000
	fstp	DWORD PTR tv142[esp+12]
	fld	DWORD PTR tv142[esp+12]

; 4    : int main(void) { volatile float x = 1.5f; printf("hello 32-bit %g\n", fma_leaf(x, 2.0f)); return 0; }

	fstp	QWORD PTR [esp]
	push	OFFSET ??_C@_0BB@CDJFNODP@hello?532?9bit?5?$CFg?6@
	call	_printf
	xor	eax, eax
	add	esp, 16					; 00000010H
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\james\i76-map\tools\env-check\cl-hello\hello.c
;	COMDAT _fma_leaf
_TEXT	SEGMENT
tv131 = 8						; size = 4
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_fma_leaf PROC						; COMDAT

; 3    : float __cdecl fma_leaf(float a, float b) { return a * b + 1.0f; }

	fld	DWORD PTR _a$[esp-4]
	fmul	DWORD PTR _b$[esp-4]
	fadd	QWORD PTR __real@3ff0000000000000
	fstp	DWORD PTR tv131[esp-4]
	fld	DWORD PTR tv131[esp-4]
	ret	0
_fma_leaf ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT

; 956  :     {

	push	esi

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);
; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H

; 961  :         __crt_va_end(_ArgList);
; 962  :         return _Result;

	pop	esi

; 963  :     }

	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H

; 646  :     }

	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
