# GENERATED by tools\harness\make-harness.py from autotest\enter-mission5.ps1 - edit the generator, not this file.
<#
  enter-mission5-pristine.ps1 - load the bookmarked save at TRIP mission 5 (the canyon-jump mission).

  Ported to the H0 build by tools\harness\make-harness.py; needs save002 in the SANDBOX game folder.
  Mission 5 is the canonical "high FPS breaks the game" test case: the scripted canyon jump is
  said to become impossible above 20 fps. Reaching it needs a save, so this drives the
  LOAD BOOKMARK path rather than NEW TRIP.

  Requires save002 (mission 5) in the game folder - check with:
      python ..\..\i76-everywhere\i76-save-editor.py --dir <gamedir> --list

  Flow (all coordinates calibrated, see lib/maplib.ps1):
    intro skip -> TRIP -> LOAD BOOKMARK -> SCENE 5 -> LOAD
    -> Car/Van Inventory (ACCEPT SALVAGE) -> Build and Repair (DONE)
    -> intro cutscene skip -> gameplay (verified by entities appearing)
#>
# -SceneY picks which bookmark row to load (SCENE 5 = 782; each row is ~50 px apart,
# SCENE 6 = 833). -StopAtGarage leaves you on the Build and Repair form so weapons can be
# equipped before entering the mission.
param([switch]$NoLaunch, [string]$GameDir = "C:\Users\james\i76-uncap-lab\game",
      [string]$Exe = "i76_pristine_fix.exe", [string]$ProcName = "i76_pristine_fix",
      [string]$CaptureId = ("launch-" + (Get-Date -Format "yyyyMMdd-HHmmss")), [int]$SettleSeconds = 9,
      [int]$SceneY = 782, [switch]$StopAtGarage)
$ErrorActionPreference = 'Stop'
$AutotestLib = "C:\Users\james\i76-uncap-lab\autotest\lib"   # (a)
. "$AutotestLib\focuslib.ps1"; . "$AutotestLib\inputlib.ps1"
. "$AutotestLib\maplib.ps1";   . "$AutotestLib\memlib.ps1"
. "$AutotestLib\simlib.ps1"
# --- harness overrides (tools\harness\make-harness.py) ---------------------------------------
# (b) focuslib's Get-GamePid matches process names i76/nitro only; the H0 build is i76_pristine_fix.exe.
function Get-GamePid {
    Get-Process -Name $ProcName -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -and $_.Path -like "*i76-uncap-lab*" } | Select-Object -First 1
}
# (e) H10 runbook rule: never run the blocking focus dance against a window that is not pumping
#     (the shell's modal dialogs). SetCursorPos + mouse_event still work in that state.
function Focus-Game($p) {
    if (-not (Test-WindowPumping $p.MainWindowHandle)) {
        Write-Warning "game window is not pumping (modal shell dialog?) - skipping the focus calls"
        return $false
    }
    return (Force-Foreground $p.MainWindowHandle)
}
# (f) maplib's Init-CursorMap ran at dot-source time and looked for `i76`/`nitro`; recompute the
#     screen-side transform from THIS process's client rect (same math as maplib, kept in step by hand).
function Sync-CursorMap($p) {
    $before = "UiLeft={0} UiTop={1} UnitPx={2} UnitPxX={3}" -f $script:UI_LEFT, $script:UI_TOP, $script:UI_U, $script:UI_UX
    $rc = New-Object WinRect+RECT
    if (-not [WinRect]::GetClientRect($p.MainWindowHandle, [ref]$rc)) { Write-Warning "GetClientRect failed; keeping $before"; return }
    $pt = New-Object WinRect+POINT; [void][WinRect]::ClientToScreen($p.MainWindowHandle, [ref]$pt)
    if ($rc.R -le 0 -or $rc.B -le 0) { Write-Warning "empty client rect; keeping $before"; return }
    $winW = [double]$rc.R; $winH = [double]$rc.B; $winX = [double]$pt.X; $winY = [double]$pt.Y
    $rw = 1680.0; $rh = 1050.0; $mode = 'stretched_ar'
    $conf = Join-Path $GameDir 'dgVoodoo.conf'
    if (Test-Path $conf) {
        $m = Select-String -Path $conf -Pattern '^\s*Resolution\s*=\s*(\d+)\s*x\s*(\d+)' | Select-Object -First 1
        if ($m) { $rw = [double]$m.Matches[0].Groups[1].Value; $rh = [double]$m.Matches[0].Groups[2].Value }
        $s = Select-String -Path $conf -Pattern '^\s*ScalingMode\s*=\s*(\S+)' | Select-Object -First 1
        if ($s) { $mode = $s.Matches[0].Groups[1].Value.ToLower() }
    }
    $ch = $winH; $cw = $ch * ($rw / $rh)
    if ($cw -gt $winW) { $cw = $winW; $ch = $cw * ($rh / $rw) }
    $cl = $winX + ($winW - $cw) / 2.0; $ct = $winY + ($winH - $ch) / 2.0
    if ($mode -like '*_ar' -or $mode -eq 'centered' -or $mode -eq 'unspecified') {
        $u = $ch / 480.0; $pillarUnits = (($cw / $u) - 640.0) / 2.0
        $script:UI_U = $u; $script:UI_UX = $u; $script:UI_LEFT = $cl + $pillarUnits * $u
    } else {
        $u = $ch / 480.0; $script:UI_U = $u; $script:UI_UX = $cw / 640.0; $script:UI_LEFT = $cl
    }
    $script:UI_TOP = $ct; $script:FR_L = $cl; $script:FR_T = $ct; $script:FR_W = $cw; $script:FR_H = $ch
    $after = "UiLeft={0} UiTop={1} UnitPx={2} UnitPxX={3}" -f $script:UI_LEFT, $script:UI_TOP, $script:UI_U, $script:UI_UX
    Write-Host ("cursor map: dot-source fallback [{0}] -> from client rect {1}x{2}@{3},{4} [{5}]" -f $before, $rc.R, $rc.B, $pt.X, $pt.Y, $after) -ForegroundColor DarkGray
}
# (b) memlib's Mem-Open matches i76/nitro only; same body, harness process lookup.
function Mem-Open {
    param([string]$RequirePath = 'i76-uncap-lab', [switch]$Write)
    $proc = Get-GamePid
    if (-not $proc) { throw "Interstate '76 ($ProcName, path *$RequirePath*) is not running." }
    $access = if ($Write) { 0x38 } else { 0x10 }   # VM_OP|VM_READ|VM_WRITE : VM_READ
    $h = [I76Mem]::OpenProcess($access, $false, $proc.Id)
    if ($h -eq [IntPtr]::Zero) { throw "OpenProcess failed (same user as the game?)." }
    [pscustomobject]@{ Proc = $proc; H = $h; Buf4 = (New-Object byte[] 4) }
}


if (-not $NoLaunch) {
    Get-GamePid | Stop-Process -Force -EA SilentlyContinue
    Start-Sleep -Seconds 2
    # (c) H0/H10: the launch goes through tools\launch.ps1 (md5 gate, session gate, which_build stamp);
    #     exit 0 = launched and H0 PASS. Anything else stops here with the launcher's own reason.
    & powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Users\james\i76-map\tools\launch.ps1" -GameDir $GameDir -Exe $Exe -CaptureId $CaptureId -SettleSeconds $SettleSeconds
    if ($LASTEXITCODE -ne 0) { throw "launch.ps1 exit $LASTEXITCODE (0 = launched + H0 pass; 3 md5 refused; 4 session/RDP refused; 5 exited early; 1 H0 FAIL)" }
}
$proc = Get-GamePid; if (-not $proc) { throw "game not running ($ProcName under i76-uncap-lab; launch with tools\launch.ps1 first)" }
Sync-CursorMap $proc   # (f)
Focus-Game $proc | Out-Null

# 1) intro -> main menu
for ($i=0; $i -lt 6; $i++) { Focus-Game $proc|Out-Null; Send-Key $VK.ESC; Start-Sleep -Milliseconds 300; Send-Key $VK.ENTER; Start-Sleep -Milliseconds 800 }

# 2) TRIP -> LOAD BOOKMARK
[Inp]::SetCursorPos(243,298); Start-Sleep -Milliseconds 250
[Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 60;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)
Start-Sleep -Milliseconds 800
[Inp]::SetCursorPos(243,298); Start-Sleep -Milliseconds 120
[Inp]::SetCursorPos(298,346); Start-Sleep -Milliseconds 300
[Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 60;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)
Start-Sleep -Seconds 3

# 3) pick SCENE 5, LOAD
Click-Screen 1370 $SceneY 400          # scene row (SCENE 5 default)
Start-Sleep -Milliseconds 600
Click-Screen 1817 1284 500         # LOAD
Start-Sleep -Seconds 7

# 4) garage screens
Click-Screen 1995 1379 500         # ACCEPT SALVAGE  (Car/Van Inventory)
Start-Sleep -Seconds 4
if ($StopAtGarage) {
    Write-Host "Stopped on the BUILD AND REPAIR form - equip weapons, then click DONE." -ForegroundColor Yellow
    exit 0
}
Click-Screen 2007 1379 500         # DONE            (Build and Repair)
Start-Sleep -Seconds 5

# 5) skip the mission cutscene; gameplay is confirmed by the entity table filling
$ctx = Mem-Open
$ok = $false
for ($i=0; $i -lt 25; $i++) {
    if ((Mem-InMission $ctx) -and (@(Mem-Entities $ctx).Count -gt 0)) { $ok = $true; break }
    Focus-Game $proc | Out-Null
    Send-Key $VK.ESC; Start-Sleep -Milliseconds 250
    [Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 50;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)
    Start-Sleep -Milliseconds 1000
}
if ($ok) {
    $e = @(Mem-Entities $ctx)
    Write-Host ("IN MISSION 5 - {0} entities, sim running: {1}" -f $e.Count, (Ensure-SimRunning $ctx)) -ForegroundColor Green
} else { Write-Host "did not reach mission 5 gameplay" -ForegroundColor Red }
Mem-Close $ctx
exit ($(if ($ok) { 0 } else { 1 }))
