# GENERATED by tools\harness\make-harness.py from autotest\enter-training.ps1 - edit the generator, not this file.
<#
  enter-training-pristine.ps1 - launch (via tools\launch.ps1, H0 build i76_pristine_fix.exe) into the TRIP training mission and bring the car to a stop.

  The training mission is the best stage for animation/per-frame work: it starts you on open
  flat desert with a large clear sky, and (unlike melee) there is no combat to end the run.
  The car starts rolling at ~15 m/s, so this brakes it to a halt - a stationary car means the
  view is not moving and pixel/animation measurements are not swamped by camera motion.

  TRAINING lives at UI (113,351) under TRIP (243,298) - read off a Capture-UI screenshot.
#>
param([switch]$NoLaunch, [switch]$NoStop, [string]$GameDir = "C:\Users\james\i76-uncap-lab\game",
      [string]$Exe = "i76_pristine_fix.exe", [string]$ProcName = "i76_pristine_fix",
      [string]$CaptureId = ("launch-" + (Get-Date -Format "yyyyMMdd-HHmmss")), [int]$SettleSeconds = 9)
$ErrorActionPreference = 'Stop'
$AutotestLib = "C:\Users\james\i76-uncap-lab\autotest\lib"   # (a)
. "$AutotestLib\focuslib.ps1"; . "$AutotestLib\inputlib.ps1"
. "$AutotestLib\maplib.ps1";   . "$AutotestLib\memlib.ps1"
. "$AutotestLib\simlib.ps1"
# --- harness overrides (tools\harness\make-harness.py) ---------------------------------------
# (b) focuslib's Get-GamePid matches process names i76/nitro only; the H0 build is i76_pristine_fix.exe.
function Get-GamePid {
    Get-Process -Name $ProcName -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -and $_.Path -like "*i76-uncap-lab*" } | Select-Object -First 1
}
# (e) H10 runbook rule: never run the blocking focus dance against a window that is not pumping
#     (the shell's modal dialogs). SetCursorPos + mouse_event still work in that state.
function Focus-Game($p) {
    if (-not (Test-WindowPumping $p.MainWindowHandle)) {
        Write-Warning "game window is not pumping (modal shell dialog?) - skipping the focus calls"
        return $false
    }
    return (Force-Foreground $p.MainWindowHandle)
}
# (f) maplib's Init-CursorMap ran at dot-source time and looked for `i76`/`nitro`; recompute the
#     screen-side transform from THIS process's client rect (same math as maplib, kept in step by hand).
function Sync-CursorMap($p) {
    $before = "UiLeft={0} UiTop={1} UnitPx={2} UnitPxX={3}" -f $script:UI_LEFT, $script:UI_TOP, $script:UI_U, $script:UI_UX
    $rc = New-Object WinRect+RECT
    if (-not [WinRect]::GetClientRect($p.MainWindowHandle, [ref]$rc)) { Write-Warning "GetClientRect failed; keeping $before"; return }
    $pt = New-Object WinRect+POINT; [void][WinRect]::ClientToScreen($p.MainWindowHandle, [ref]$pt)
    if ($rc.R -le 0 -or $rc.B -le 0) { Write-Warning "empty client rect; keeping $before"; return }
    $winW = [double]$rc.R; $winH = [double]$rc.B; $winX = [double]$pt.X; $winY = [double]$pt.Y
    $rw = 1680.0; $rh = 1050.0; $mode = 'stretched_ar'
    $conf = Join-Path $GameDir 'dgVoodoo.conf'
    if (Test-Path $conf) {
        $m = Select-String -Path $conf -Pattern '^\s*Resolution\s*=\s*(\d+)\s*x\s*(\d+)' | Select-Object -First 1
        if ($m) { $rw = [double]$m.Matches[0].Groups[1].Value; $rh = [double]$m.Matches[0].Groups[2].Value }
        $s = Select-String -Path $conf -Pattern '^\s*ScalingMode\s*=\s*(\S+)' | Select-Object -First 1
        if ($s) { $mode = $s.Matches[0].Groups[1].Value.ToLower() }
    }
    $ch = $winH; $cw = $ch * ($rw / $rh)
    if ($cw -gt $winW) { $cw = $winW; $ch = $cw * ($rh / $rw) }
    $cl = $winX + ($winW - $cw) / 2.0; $ct = $winY + ($winH - $ch) / 2.0
    if ($mode -like '*_ar' -or $mode -eq 'centered' -or $mode -eq 'unspecified') {
        $u = $ch / 480.0; $pillarUnits = (($cw / $u) - 640.0) / 2.0
        $script:UI_U = $u; $script:UI_UX = $u; $script:UI_LEFT = $cl + $pillarUnits * $u
    } else {
        $u = $ch / 480.0; $script:UI_U = $u; $script:UI_UX = $cw / 640.0; $script:UI_LEFT = $cl
    }
    $script:UI_TOP = $ct; $script:FR_L = $cl; $script:FR_T = $ct; $script:FR_W = $cw; $script:FR_H = $ch
    $after = "UiLeft={0} UiTop={1} UnitPx={2} UnitPxX={3}" -f $script:UI_LEFT, $script:UI_TOP, $script:UI_U, $script:UI_UX
    Write-Host ("cursor map: dot-source fallback [{0}] -> from client rect {1}x{2}@{3},{4} [{5}]" -f $before, $rc.R, $rc.B, $pt.X, $pt.Y, $after) -ForegroundColor DarkGray
}
# (b) memlib's Mem-Open matches i76/nitro only; same body, harness process lookup.
function Mem-Open {
    param([string]$RequirePath = 'i76-uncap-lab', [switch]$Write)
    $proc = Get-GamePid
    if (-not $proc) { throw "Interstate '76 ($ProcName, path *$RequirePath*) is not running." }
    $access = if ($Write) { 0x38 } else { 0x10 }   # VM_OP|VM_READ|VM_WRITE : VM_READ
    $h = [I76Mem]::OpenProcess($access, $false, $proc.Id)
    if ($h -eq [IntPtr]::Zero) { throw "OpenProcess failed (same user as the game?)." }
    [pscustomobject]@{ Proc = $proc; H = $h; Buf4 = (New-Object byte[] 4) }
}


if (-not $NoLaunch) {
    Get-GamePid | Stop-Process -Force -EA SilentlyContinue
    Start-Sleep -Seconds 2
    # (c) H0/H10: the launch goes through tools\launch.ps1 (md5 gate, session gate, which_build stamp);
    #     exit 0 = launched and H0 PASS. Anything else stops here with the launcher's own reason.
    & powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Users\james\i76-map\tools\launch.ps1" -GameDir $GameDir -Exe $Exe -CaptureId $CaptureId -SettleSeconds $SettleSeconds
    if ($LASTEXITCODE -ne 0) { throw "launch.ps1 exit $LASTEXITCODE (0 = launched + H0 pass; 3 md5 refused; 4 session/RDP refused; 5 exited early; 1 H0 FAIL)" }
}
$proc = Get-GamePid; if (-not $proc) { throw "game not running ($ProcName under i76-uncap-lab; launch with tools\launch.ps1 first)" }
Sync-CursorMap $proc   # (f)
Focus-Game $proc | Out-Null
for ($i=0; $i -lt 6; $i++) { Focus-Game $proc|Out-Null; Send-Key $VK.ESC; Start-Sleep -Milliseconds 300; Send-Key $VK.ENTER; Start-Sleep -Milliseconds 800 }

[Inp]::SetCursorPos(243,298); Start-Sleep -Milliseconds 250          # TRIP
[Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 60;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)
Start-Sleep -Milliseconds 900
[Inp]::SetCursorPos(243,298); Start-Sleep -Milliseconds 150
Click-UI 113 351 400                                                  # TRAINING
Start-Sleep -Seconds 4

$ctx = Mem-Open
$ok = $false
for ($i=0; $i -lt 30; $i++) {
    if ((Mem-InMission $ctx) -and (@(Mem-Entities $ctx).Count -gt 0)) { $ok = $true; break }
    Focus-Game $proc | Out-Null
    Send-Key $VK.ESC; Start-Sleep -Milliseconds 250
    [Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 50;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)
    Start-Sleep -Milliseconds 900
}
if ($ok -and -not $NoStop) {
    # the mission starts you rolling at ~15 m/s; brake and handbrake to a standstill
    for ($i=0; $i -lt 25; $i++) { Send-Key $VK.S 50; Start-Sleep -Milliseconds 70 }
    Send-Key ([byte]0x43) 100
    Start-Sleep -Seconds 3
}
if ($ok) {
    $p = Mem-Player $ctx
    Write-Host ("IN TRAINING - speed {0:N2} m/s, {1} entities, sim {2}" -f $p.Speed, (@(Mem-Entities $ctx).Count), (Ensure-SimRunning $ctx)) -ForegroundColor Green
} else { Write-Host "did not reach training gameplay" -ForegroundColor Red }
Mem-Close $ctx
exit ($(if ($ok) { 0 } else { 1 }))
