# GENERATED by tools\harness\make-harness.py from autotest\enter-melee.ps1 - edit the generator, not this file.
<#
  enter-melee-pristine.ps1 - launch I'76 (sandbox, H0 build i76_pristine_fix.exe) and drive the menus into an INSTANT MELEE,
  fully unattended. Returns once the player entity is live (in a mission).

  This is the recovery path for the whole effort: the game crashes easily during RE, and
  the menus need a DirectInput cursor mapped into the screen's upper-left (see maplib.ps1).
  Encodes the calibrated path discovered 2026-08-08:
    intro -> ESC/ENTER skips -> main menu
    MELEE (OS 450,300) -> AUTO MELEE (490,360) -> INSTANT MELEE (535,375)
    Driver Entry Form -> ENTER AREA (screen 1648,1385 via calibrated map)
  In-mission is detected from memory: player entity [[[0x54a264]]+0x70] != 0.

  Usage:
    powershell -ExecutionPolicy Bypass -File tools\harness\enter-melee-pristine.ps1                 # launch via tools\launch.ps1 + enter
    powershell -ExecutionPolicy Bypass -File tools\harness\enter-melee-pristine.ps1 -NoLaunch -Area AirBase  # already running (the sitting)
#>
<#
  -Area selects the ARENA on the Driver Entry Form. Terrain slope contaminates any speed or
  drag measurement (a car that wanders downhill gains speed), so physics tests should use a
  FLAT arena - 'SlickTrack' or 'AirBase' - not the default hilly Tombstone.
#>
param([switch]$NoLaunch, [switch]$KeepAI, [string]$GameDir = "C:\Users\james\i76-uncap-lab\game",
      [string]$Exe = "i76_pristine_fix.exe", [string]$ProcName = "i76_pristine_fix",
      [string]$CaptureId = ("launch-" + (Get-Date -Format "yyyyMMdd-HHmmss")), [int]$SettleSeconds = 8,
      [ValidateSet('','Crater','Dunes','AirBase','Suburbia','SlickTrack','Tombstone')][string]$Area = '',
      # stop early so a human can take over from a known point (used by record-session.ps1)
      [switch]$StopAtMainMenu, [switch]$StopAtForm)
$ErrorActionPreference = 'Stop'
$AutotestLib = "C:\Users\james\i76-uncap-lab\autotest\lib"   # (a)
. "$AutotestLib\focuslib.ps1"; . "$AutotestLib\inputlib.ps1"; . "$AutotestLib\maplib.ps1"
# --- harness overrides (tools\harness\make-harness.py) ---------------------------------------
# (b) focuslib's Get-GamePid matches process names i76/nitro only; the H0 build is i76_pristine_fix.exe.
function Get-GamePid {
    Get-Process -Name $ProcName -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -and $_.Path -like "*i76-uncap-lab*" } | Select-Object -First 1
}
# (e) H10 runbook rule: never run the blocking focus dance against a window that is not pumping
#     (the shell's modal dialogs). SetCursorPos + mouse_event still work in that state.
function Focus-Game($p) {
    if (-not (Test-WindowPumping $p.MainWindowHandle)) {
        Write-Warning "game window is not pumping (modal shell dialog?) - skipping the focus calls"
        return $false
    }
    return (Force-Foreground $p.MainWindowHandle)
}
# (f) maplib's Init-CursorMap ran at dot-source time and looked for `i76`/`nitro`; recompute the
#     screen-side transform from THIS process's client rect (same math as maplib, kept in step by hand).
function Sync-CursorMap($p) {
    $before = "UiLeft={0} UiTop={1} UnitPx={2} UnitPxX={3}" -f $script:UI_LEFT, $script:UI_TOP, $script:UI_U, $script:UI_UX
    $rc = New-Object WinRect+RECT
    if (-not [WinRect]::GetClientRect($p.MainWindowHandle, [ref]$rc)) { Write-Warning "GetClientRect failed; keeping $before"; return }
    $pt = New-Object WinRect+POINT; [void][WinRect]::ClientToScreen($p.MainWindowHandle, [ref]$pt)
    if ($rc.R -le 0 -or $rc.B -le 0) { Write-Warning "empty client rect; keeping $before"; return }
    $winW = [double]$rc.R; $winH = [double]$rc.B; $winX = [double]$pt.X; $winY = [double]$pt.Y
    $rw = 1680.0; $rh = 1050.0; $mode = 'stretched_ar'
    $conf = Join-Path $GameDir 'dgVoodoo.conf'
    if (Test-Path $conf) {
        $m = Select-String -Path $conf -Pattern '^\s*Resolution\s*=\s*(\d+)\s*x\s*(\d+)' | Select-Object -First 1
        if ($m) { $rw = [double]$m.Matches[0].Groups[1].Value; $rh = [double]$m.Matches[0].Groups[2].Value }
        $s = Select-String -Path $conf -Pattern '^\s*ScalingMode\s*=\s*(\S+)' | Select-Object -First 1
        if ($s) { $mode = $s.Matches[0].Groups[1].Value.ToLower() }
    }
    $ch = $winH; $cw = $ch * ($rw / $rh)
    if ($cw -gt $winW) { $cw = $winW; $ch = $cw * ($rh / $rw) }
    $cl = $winX + ($winW - $cw) / 2.0; $ct = $winY + ($winH - $ch) / 2.0
    if ($mode -like '*_ar' -or $mode -eq 'centered' -or $mode -eq 'unspecified') {
        $u = $ch / 480.0; $pillarUnits = (($cw / $u) - 640.0) / 2.0
        $script:UI_U = $u; $script:UI_UX = $u; $script:UI_LEFT = $cl + $pillarUnits * $u
    } else {
        $u = $ch / 480.0; $script:UI_U = $u; $script:UI_UX = $cw / 640.0; $script:UI_LEFT = $cl
    }
    $script:UI_TOP = $ct; $script:FR_L = $cl; $script:FR_T = $ct; $script:FR_W = $cw; $script:FR_H = $ch
    $after = "UiLeft={0} UiTop={1} UnitPx={2} UnitPxX={3}" -f $script:UI_LEFT, $script:UI_TOP, $script:UI_U, $script:UI_UX
    Write-Host ("cursor map: dot-source fallback [{0}] -> from client rect {1}x{2}@{3},{4} [{5}]" -f $before, $rc.R, $rc.B, $pt.X, $pt.Y, $after) -ForegroundColor DarkGray
}

Add-Type @"
using System;using System.Runtime.InteropServices;
public class EM{ [DllImport("kernel32.dll")] public static extern IntPtr OpenProcess(uint a,bool i,int p);
 [DllImport("kernel32.dll")] public static extern bool ReadProcessMemory(IntPtr h,IntPtr a,byte[] b,int s,out int r);}
"@
function Player-Entity([int]$procId) {
    $h = [EM]::OpenProcess(0x10, $false, $procId); if ($h -eq [IntPtr]::Zero) { return 0 }
    function rd32([int64]$a){$b=New-Object byte[] 4;$n=0;if([EM]::ReadProcessMemory($h,[IntPtr]$a,$b,4,[ref]$n)){[BitConverter]::ToInt32($b,0)}else{0}}
    $w = rd32 0x54a264; if (-not $w) { return 0 }
    $s = rd32 $w; if (-not $s) { return 0 }
    return (rd32 ($s + 0x70))
}

if (-not $NoLaunch) {
    Get-GamePid | Stop-Process -Force -EA SilentlyContinue
    Start-Sleep -Seconds 1
    # (c) H0/H10: the launch goes through tools\launch.ps1 (md5 gate, session gate, which_build stamp);
    #     exit 0 = launched and H0 PASS. Anything else stops here with the launcher's own reason.
    & powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Users\james\i76-map\tools\launch.ps1" -GameDir $GameDir -Exe $Exe -CaptureId $CaptureId -SettleSeconds $SettleSeconds
    if ($LASTEXITCODE -ne 0) { throw "launch.ps1 exit $LASTEXITCODE (0 = launched + H0 pass; 3 md5 refused; 4 session/RDP refused; 5 exited early; 1 H0 FAIL)" }
}
$proc = Get-GamePid; if (-not $proc) { throw "game not running ($ProcName under i76-uncap-lab; launch with tools\launch.ps1 first)" }
Sync-CursorMap $proc   # (f)
Focus-Game $proc | Out-Null

# 1) skip intro crawl -> main menu (tap a few times)
for ($i=0; $i -lt 6; $i++) { Focus-Game $proc|Out-Null; Send-Key $VK.ESC; Start-Sleep -Milliseconds 300; Send-Key $VK.ENTER; Start-Sleep -Milliseconds 800 }

if ($StopAtMainMenu) { Write-Host "Stopped at the MAIN MENU." -ForegroundColor Yellow; exit 0 }

# 2) MELEE -> AUTO MELEE -> INSTANT MELEE (OS-space path, keeps chain open)
Focus-Game $proc | Out-Null
[Inp]::SetCursorPos(450,300); Start-Sleep -Milliseconds 250
[Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 60;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)   # click MELEE
Start-Sleep -Milliseconds 600
[Inp]::SetCursorPos(450,300); Start-Sleep -Milliseconds 120
[Inp]::SetCursorPos(490,360); Start-Sleep -Milliseconds 250
[Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 60;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)   # click AUTO MELEE
Start-Sleep -Milliseconds 600
[Inp]::SetCursorPos(450,300); Start-Sleep -Milliseconds 100
[Inp]::SetCursorPos(490,360); Start-Sleep -Milliseconds 100
[Inp]::SetCursorPos(535,375); Start-Sleep -Milliseconds 250
[Inp]::mouse_event(0x2,0,0,0,[IntPtr]::Zero);Start-Sleep -Milliseconds 60;[Inp]::mouse_event(0x4,0,0,0,[IntPtr]::Zero)   # click INSTANT MELEE
Start-Sleep -Milliseconds 2500

if ($StopAtForm) { Write-Host "Stopped on the DRIVER ENTRY FORM." -ForegroundColor Yellow; exit 0 }

# 3) Driver Entry Form: pick the arena, set A.I. DRIVERS to 0, then ENTER AREA
Focus-Game $proc | Out-Null
if ($Area) {
    # AREA OF PLAY rows in UI (640x480) coordinates, read straight off a Capture-UI screenshot.
    # Terrain matters for physics tests: AirBase and SlickTrack are flat (no airtime at all),
    # Dunes/Crater/Tombstone have hills - use those for anything involving jumps or rotation.
    $areaY = @{ Crater = 157; Dunes = 174; AirBase = 191; Suburbia = 208; SlickTrack = 226; Tombstone = 242 }
    Click-UI 80 $areaY[$Area] 400
    Start-Sleep -Milliseconds 500
}
# A.I. DRIVERS [-] is UI (159,295) per lib/maplib.ps1. The old screen-space coordinate here was
# from a superseded (wrong) calibration and silently did nothing, so "empty" arenas still had an
# AI car in them - which collides with the player and corrupts any rotation/spin measurement.
if (-not $KeepAI) { Click-UI 159 295 400; Start-Sleep -Milliseconds 300 }
Click-Screen 1648 1385 500
Start-Sleep -Seconds 2

# 4) wait for in-mission
$deadline = (Get-Date).AddSeconds(20); $ent = 0
while ((Get-Date) -lt $deadline) {
    $ent = Player-Entity $proc.Id
    if ($ent -ne 0) { break }
    Start-Sleep -Milliseconds 500
}
if ($ent -ne 0) { Write-Host ("IN MISSION - player entity 0x{0:X}" -f $ent) -ForegroundColor Green; exit 0 }
else { Write-Host "Did not reach mission (menu nav may have drifted)." -ForegroundColor Red; exit 1 }
