Version = 0x287

[General]
OutputAPI = d3d11_fl10_1
FullScreenMode = false
ScalingMode = stretched_ar

[Glide]
VideoCard = voodoo_graphics
OnboardRAM = 4
MemorySizeOfTMU = 2048
NumberOfTMUs = 1
Resolution = 4608x2880
Antialiasing = 8x
3DfxWatermark = true
3DfxSplashScreen = false
