#!/usr/bin/env python3
r"""gendoc.py - generate the layout tables of data\FORMATS.md from the live layouts + data\roundtrip.json.

    python data\fmt\gendoc.py            -> data\FORMATS-tables.md (included by FORMATS.md)
Tables come from the same Struct objects the parsers use, so the document cannot drift from the code.
"""
import os, sys, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import layouts, schema  # noqa: E402
import other_formats  # noqa: E402

DATA = os.path.dirname(HERE)


def table(typ):
    rows = schema.layout_rows(typ)
    out = ["| off | type | field | class | meaning | citation |", "|---|---|---|---|---|---|"]
    for off, t, name, k, meaning, cite in rows:
        o = "" if off is None else "0x%x" % off
        out.append("| %s | %s | %s | %s | %s | %s |" % (o, t, name, k, (meaning or "").replace("|", "/"), (cite or "").replace("|", "/")))
    return "\n".join(out)


def main():
    rt = json.load(open(os.path.join(DATA, "roundtrip.json"), encoding="utf-8"))
    L = ["<!-- generated by data/fmt/gendoc.py from the parser layouts; do not edit by hand -->", "",
         "# Layout tables (generated)", "",
         "Offsets are body offsets (after the 8-byte BWD2 chunk header). `class`: cited = consuming instruction in i76.exe;",
         "unused = the loader provably never reads it; typed = named/typed without an exe citation; unknown = explicit unknown run.", ""]
    L.append("## Byte coverage per format (from data/roundtrip.json, %s)" % rt["time"])
    L.append("")
    L.append("| format | files | bytes | round trip | cited | unused | typed | unknown |")
    L.append("|---|---|---|---|---|---|---|---|")
    for f in rt["families"]:
        c = f["coverage_pct"]
        L.append("| %s | %d | %d | %s | %.2f%% | %.2f%% | %.2f%% | %.2f%% |" % (
            f["family"], f["files"], f["bytes"], "0 diffs" if f["diff_files"] == 0 and not f["parse_errors"] else "%d diffs %d errs" % (f["diff_files"], len(f["parse_errors"])),
            c["cited"], c["unused"], c["typed"], c["unknown"]))
    t = rt["totals"]
    tot = sum(t["coverage"].values()) or 1
    L.append("| **all** | %d | %d | %s | %.2f%% | %.2f%% | %.2f%% | %.2f%% |" % (
        t["files"], t["bytes"], rt["verdict"], *(100.0 * t["coverage"][k] / tot for k in ("cited", "unused", "typed", "unknown"))))
    L.append("")
    seen = set()
    by_fam = {}
    for (fam, parent, tag), lay in sorted(layouts.REGISTRY.items()):
        if tag in ("EXIT",) or lay.typ is None and not lay.doc:
            continue
        by_fam.setdefault(fam, []).append((parent, tag, lay))
    for fam in sorted(by_fam):
        L.append("## BWD2 family `%s`" % fam)
        L.append("")
        for parent, tag, lay in by_fam[fam]:
            key = id(lay)
            head = "### %s%s" % (parent + "/" if parent and parent != "*" else "", tag)
            L.append(head)
            L.append("")
            if key in seen:
                L.append("Same layout as above.")
                L.append("")
                continue
            seen.add(key)
            if lay.doc:
                L.append(lay.doc)
                L.append("")
            if lay.typ is not None:
                L.append(table(lay.typ))
                L.append("")
            for sub in getattr(lay, "subs", []):
                L.append(table(sub))
                L.append("")
    L.append("## Other formats")
    L.append("")
    for ext in sorted(other_formats.REG):
        h = other_formats.REG[ext]
        L.append("### %s" % ext)
        L.append("")
        L.append(h.method)
        L.append("")
    for name in ("GEO", "GEO_FACE", "GEO_VREF", "VQM", "MAP", "CBK", "TMT", "GPW", "TAB", "SMK_HDR"):
        typ = getattr(other_formats, name, None)
        if typ is not None:
            L.append("#### %s" % typ.name)
            L.append("")
            L.append(table(typ))
            L.append("")
    import mw2db
    L.append("## DATABASE.MW2 (i76shell.dll; layouts from mw2db.LAYOUT, addresses are shell VAs)")
    L.append("")
    for name, rows in mw2db.LAYOUT.items():
        L.append("#### %s" % name)
        L.append("")
        L.append("| off | type | field | class | meaning | citation |")
        L.append("|---|---|---|---|---|---|")
        for row in rows:
            L.append("| " + " | ".join(c.replace("|", "/") for c in row) + " |")
        L.append("")
    L.append("#### What the shell loads each item for (mw2db.USES)")
    L.append("")
    L.append("| item | use | load site |")
    L.append("|---|---|---|")
    for k in sorted(mw2db.USES):
        L.append("| 0x%02x | %s | %s |" % (k, mw2db.USES[k][0], mw2db.USES[k][1]))
    L.append("")
    out = os.path.join(DATA, "FORMATS-tables.md")
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote", out, len(L), "lines")


if __name__ == "__main__":
    main()
