#!/usr/bin/env python3
"""Generate a gamepad-rumble envelope table from Interstate '76 sound effects.

Reads the .gpw effect sounds out of the user's own I76.ZFS, decodes them
(GPW = 28-byte "GAS0" wrapper + standard RIFF/WAVE, PCM mono 8-bit 11025 Hz),
computes a windowed-RMS amplitude envelope per sound, and writes a small
"name=v0,v1,..." table (values 0-100) that the AHK rumble layer can read at
startup and play through XInputSetState instead of fixed-length pulses.

The output is DERIVED DATA from the user's own game files and is generated
locally — it is gitignored, not committed (same rule as the built SMACKW32.DLL).

Usage:
  gpw-envelopes.py <I76.ZFS | game-dir> [--out rumble-envelopes.ini]
                   [--window-ms 25] [--max-s 1.5] [--only substr] [--list]

Envelope format, one line per sound (INI-ish, comments start with ';'):
  whmgun=84,91,85,91,...      ; values = RMS per window, normalized peak=100
A consumer plays one value per window-ms tick, scaling its motor amplitude.
"""
import argparse, io, os, struct, sys, wave

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import zfs_extract  # repo tool: parse() + payload decompression


def decode_gpw(payload: bytes):
    """Return (samplerate, list-of-centered-floats) from a GPW payload."""
    riff = payload.find(b"RIFF")
    if riff < 0:
        raise ValueError("no RIFF chunk")
    w = wave.open(io.BytesIO(payload[riff:]))
    n, width, rate = w.getnframes(), w.getsampwidth(), w.getframerate()
    raw = w.readframes(n)
    if width == 1:                      # 8-bit unsigned (the I76 norm)
        samples = [(b - 128) / 128.0 for b in raw]
    elif width == 2:
        samples = [s / 32768.0 for (s,) in struct.iter_unpack("<h", raw)]
    else:
        raise ValueError(f"unhandled sample width {width}")
    return rate, samples


def envelope(rate, samples, window_ms, max_s):
    win = max(1, int(rate * window_ms / 1000))
    samples = samples[: int(rate * max_s)]
    out = []
    for i in range(0, len(samples), win):
        chunk = samples[i : i + win]
        rms = (sum(s * s for s in chunk) / len(chunk)) ** 0.5
        out.append(rms)
    peak = max(out) if out else 0
    if peak <= 0:
        return []
    return [round(100 * v / peak) for v in out]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source", help="I76.ZFS path or the game dir containing it")
    ap.add_argument("--out", default="rumble-envelopes.ini")
    ap.add_argument("--window-ms", type=int, default=25)
    ap.add_argument("--max-s", type=float, default=1.5)
    ap.add_argument("--only", default="", help="substring filter on sound names")
    ap.add_argument("--list", action="store_true", help="list .gpw names and exit")
    args = ap.parse_args()

    src = args.source
    if os.path.isdir(src):
        src = os.path.join(src, "I76.ZFS")
    data = open(src, "rb").read()

    entries = [e for e in zfs_extract.parse(data)
               if e[0].endswith(".gpw") and args.only in e[0]]
    if args.list:
        for name, *_ in entries:
            print(name)
        return

    lines = [
        "; rumble envelope table generated by tools/gpw-envelopes.py",
        f"; source={os.path.basename(src)} window_ms={args.window_ms} "
        f"max_s={args.max_s} scale=0-100 (RMS, peak-normalized)",
        "; one value per window; play one per tick, scale motor amplitude.",
    ]
    ok = bad = 0
    for name, off, length, comp, dlen in sorted(entries):
        payload = zfs_extract.decompress(data[off : off + length], comp, dlen)
        try:
            rate, samples = decode_gpw(payload)
            env = envelope(rate, samples, args.window_ms, args.max_s)
        except Exception as ex:                       # noqa: BLE001
            print(f"  skip {name}: {ex}", file=sys.stderr)
            bad += 1
            continue
        if env:
            lines.append(f"{name[:-4]}=" + ",".join(map(str, env)))
            ok += 1
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {ok} envelopes ({bad} skipped)")


if __name__ == "__main__":
    main()
